### ISSUE TITLE
客户端并发调用uploadImage会出车祸

### ISSUE THREAD

**Issue by ssttkkl** [project-mirai/mirai-api-http#126]
## 复现代码

使用的是[Logiase/gomirai](https://github.com/Logiase/gomirai)实现的客户端，~~uploadImage部分是我交的pr所以应该不是这边的锅，而且py的也会有这个问题~~

```go
package main

import (
	"fmt"
	"github.com/Logiase/gomirai"
	"github.com/Logiase/gomirai/message"
	"github.com/sirupsen/logrus"
	"os"
	"os/signal"
	"sync"
)

const (
	qq       = 123456
	targetQQ = 987654
	url      = "http://127.0.0.1:3399"
	authKey  = "qwerty"
)

var client *gomirai.Client
var bot *gomirai.Bot

func main() {
	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)

	// 初始化Bot部分
	client = gomirai.NewClient("default", url, authKey)
	client.Logger.Level = logrus.TraceLevel
	key, err := client.Auth()
	if err != nil {
		client.Logger.Fatal(err)
	}
	bot, err = client.Verify(qq, key)
	if err != nil {
		client.Logger.Fatal(err)
	}

	// 启动3个goroutine发送图片
	var wg sync.WaitGroup
	for i := 1; i <= 3; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()

			// 传图片
			path := fmt.Sprintf("./img/%d.jpg", i)
			imgId, err := bot.UploadImage("friend", path)
			if err != nil {
				client.Logger.Error(err)
				return
			}

			// 发消息
			_, err = bot.SendFriendMessage(targetQQ, 0,
				message.PlainMessage(path), message.ImageMessage("id", imgId))
			if err != nil {
				client.Logger.Error(err)
				return
			}
			client.Logger.Info(path, " sent")
		}(i)
	}
	wg.Wait()
}

```

## Case 1：上传成功，但是都是同一张图，还有部分图直接裂开

![receiver_view_1](https://user-images.githubusercontent.com/17331698/88460632-1dff2000-ced0-11ea-83bc-859758918676.png)

```
 23:20:38 [INFO] [BOT 123456] 無銘(987654) -> [mirai:source:21863,-605524274]test start
 23:20:46 [INFO] [NETWORK] Send: LongConn.OffPicUp
 23:20:46 [INFO] [NETWORK] Send: LongConn.OffPicUp
 23:20:46 [INFO] [NETWORK] Send: LongConn.OffPicUp
 23:20:46 [INFO] [NETWORK] Recv: RequireUpload(resourceId=/123456-2114277775-D41D8CD98F00B204E9800998ECF8427E, serverIp=[-21302920, 688405616, -1331749265, 1810547383], serverPort=[8080, 8080, 80, 443], uKey=[-67, 113, -115, ...])
 23:20:46 [INFO] [NETWORK] [Http] Uploading friend image, size=251.21 KiB
 23:20:46 [INFO] [NETWORK] Recv: FileExists(resourceId=/123456-1500283458-EF27A2CE05AC8815DC72B980B3252AE5, imageInfo=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Cmd0x352$ImgInfo@f329a2f)
 23:20:46 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 23:20:46 [INFO] [NETWORK] Recv: FileExists(resourceId=/123456-821741126-EF27A2CE05AC8815DC72B980B3252AE5, imageInfo=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Cmd0x352$ImgInfo@561cbf83)
 23:20:46 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 23:20:46 [INFO] [NETWORK] Recv: MessageSvcPbSendMsg.Response.SUCCESS
 23:20:46 [INFO] [BOT 123456] Friend(987654) <- ./img/1.jpg[mirai:image:/123456-1500283458-EF27A2CE05AC8815DC72B980B3252AE5]
 23:20:46 [INFO] [NETWORK] Recv: MessageSvcPbSendMsg.Response.SUCCESS
 23:20:46 [INFO] [BOT 123456] Friend(987654) <- ./img/3.jpg[mirai:image:/123456-821741126-EF27A2CE05AC8815DC72B980B3252AE5]
 23:20:46 [INFO] [NETWORK] [Http] Uploading friend image: succeed at 463 KiB/s
 23:20:46 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 23:20:46 [INFO] [NETWORK] Recv: MessageSvcPbSendMsg.Response.SUCCESS
 23:20:46 [INFO] [BOT 123456] Friend(987654) <- ./img/2.jpg[mirai:image:/123456-2114277775-D41D8CD98F00B204E9800998ECF8427E]
```

## Case 2：只有一张上传成功，剩余都是404

![receiver_view_2 png](https://user-images.githubusercontent.com/17331698/88460634-20fa1080-ced0-11ea-962f-230f3df6f2bd.png)

```
 23:29:53 [INFO] [NETWORK] Send: LongConn.OffPicUp
 23:29:53 [INFO] [NETWORK] Send: LongConn.OffPicUp
 23:29:53 [INFO] [NETWORK] Send: LongConn.OffPicUp
 23:29:53 [INFO] [NETWORK] Recv: RequireUpload(resourceId=/123456-3712753183-9C0163A4A2BB800042A738EDF26A6805, serverIp=[1538978168, -1912062864, -1600184721, 990222372], serverPort=[8080, 8080, 80, 443], uKey=[-93, -24, -66, ...])
 23:29:53 [INFO] [NETWORK] [Http] Uploading friend image, size=647.53 KiB
 23:29:53 [INFO] [NETWORK] Recv: RequireUpload(resourceId=/123456-3571957714-9C0163A4A2BB800042A738EDF26A6805, serverIp=[1538978168, -21302920, -1448403345, -1028800329], serverPort=[8080, 8080, 80, 443], uKey=[-3, 48, 88, ...])
 23:29:53 [INFO] [NETWORK] [Http] Uploading friend image, size=647.53 KiB
 23:29:53 [INFO] [NETWORK] Recv: RequireUpload(resourceId=/123456-1456923035-4DC304CE90C70DA1D94CD3C943A82AB2, serverIp=[1538978168, 688405616, -1448403345, -1091910985], serverPort=[8080, 8080, 80, 443], uKey=[15, -89, -29, ...])
 23:29:53 [INFO] [NETWORK] [Http] Uploading friend image, size=647.53 KiB
 23:29:53 [ERROR] [MiraiAPIHTTP] io.ktor.client.features.ClientRequestException: Client request(http://htdata2.qq.com/cgi-bin/httpconn?htcmd=0x6ff0070&uin=123456&term=pc&ver=5603&filesize=663075&range=0&ukey=A3E8BE0B6224A1A144E3661B3E83D0167F1E1C7E31AFE90F64E50F6DFC1748FA1BD66D542F5C6497EE140B9D34A5F8402202DAE6A46CB353EB133623777690A50E3D6C06FBEF5FDDB0EAF89FE909BF2831A27452C2BA02FCBDBD5A5C7C2C33C25B1E51CD6505ECD088F47654C4973BDA5753597050EFB40D55268FC74CAFF05E9B3DDE3DED4289C65547C658F76126347B2F981C8520BD28F14DA33D9CDC15AEB3377BFE456904D0C75BDA275C552BF2787A0F5BBCC8CBC09EEA8DDEDF2DED3D91A84A1679DD337CC592AF08E9DFC577607E2FCE13BA2AB92B108D5325D220D1CB652B8E83D22CAFE1C914A9927D2E388EABA4295BAEB142598384D4DD3FF66565807FDA4803B08C3677D23B007B84C4571DDB1E4488AC2845A37163AAFCEE23FFEC1629F0DA472AE5820F89F7BF01E9EEC296300D301BFAF66A60E245DA83E51CDA087D2BADDE0212020DF093FA6211) invalid: 404 Not Found
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:35)
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:37)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:99)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:75)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelperKt.postImage(HighwayHelper.kt:235)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelperKt$postImage$1.invokeSuspend(HighwayHelper.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 23:29:54 [ERROR] [MiraiAPIHTTP] io.ktor.client.features.ClientRequestException: Client request(http://htdata2.qq.com/cgi-bin/httpconn?htcmd=0x6ff0070&uin=123456&term=pc&ver=5603&filesize=663075&range=0&ukey=FD30585C8D3D99F8405AE349DA5392EDDF5C777C4136DDC4061133B42E92EE80285775402BF3817DEAC7D522E2E7C7E4F219CA6671E793EFC139E6B6E461986FE3FB5C91B317D7A45C1623E83552A1D77DC26D54434B502A26FDAFD4F29696030028293993E955DACA019C62F697DCE1B839B1E487FE8ABC63470D8B04C18346D47C44C350BAD50D239156E1046A99C71ABA6CBD2A47B46E60907039112F413C8C0089CFBBB7B7CC07EF44CE6EC38168F2D4DC6247F38D700279498584EB6B3449C1FA2D612F6CE7988F6B087A069A7A19577BC8B0EA2C40C573D37C61F0551A23C5181F5AF706061C0A2021CBD05182D72AB8EB51640C4D60E57684CB7721B26B7BB4B5A8CA544E121EF427E50585265B15171731545D4563BF3CF6F0685339134CC48CB0FE0A25C621D54308F956F67753B2A9AAA1A1263FAAFE408B8312D83076D6E1D13E668BD00166667222FF37) invalid: 404 Not Found
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:35)
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:37)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:99)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.client.call.HttpClientCall.receive(HttpClientCall.kt:75)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelperKt.postImage(HighwayHelper.kt:235)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelperKt$postImage$1.invokeSuspend(HighwayHelper.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 23:29:55 [INFO] [NETWORK] [Http] Uploading friend image: succeed at 349 KiB/s
 23:29:55 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 23:29:55 [INFO] [NETWORK] Recv: MessageSvcPbSendMsg.Response.SUCCESS
 23:29:55 [INFO] [BOT 123456] Friend(987654) <- ./img/2.png[mirai:image:/123456-1456923035-4DC304CE90C70DA1D94CD3C943A82AB2]
```

**Comment by ssttkkl** [comment]
mirai-api-http：1.7.3
mirai-console：0.5.2
mirai-core-qqandroid：1.0.3

**Comment by Chenwe-i-lin** [comment]
?我试试

**Comment by Chenwe-i-lin** [comment]
全部木大.

**Comment by ryoii** [comment]
注意风控
