### ISSUE TITLE
[bug] 跑服务器上， /all 接口报404，/about可以正常访问

### ISSUE THREAD

**Issue by aboutmydreams** [project-mirai/mirai-api-http#133]
在谷歌插件调试的文档和api json中也没有发现这个/all的的接口，不知道是怎么用的
```
[2020-08-06 12:33:56,943][INFO]: launching app...
[2020-08-06 12:33:57,152][INFO]: using pure websocket to receive event
[2020-08-06 12:33:57,152][INFO]: event reveiver running...
[2020-08-06 12:33:57,164][INFO]: application shutdowning...
[2020-08-06 12:33:57,175][INFO]: goodbye :)
Traceback (most recent call last):
  File "/Users/dengwenhao/coding/project/haobot-chat-v2/main.py", line 88, in <module>
    app.launch_blocking()
  File "/usr/local/lib/python3.7/site-packages/graia/application/__init__.py", line 588, in launch_blocking
    loop.run_until_complete(fetch_method)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/graia/application/__init__.py", line 518, in ws_all_poster
    "sessionKey": self.connect_info.sessionKey
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 738, in _ws_connect
    headers=resp.headers)
aiohttp.client_exceptions.WSServerHandshakeError: 404, message='Invalid response status', url=URL('http://xxx.net/all?sessionKey=jVg31WKD')
```

**Comment by aboutmydreams** [comment]
环境都是最新的，也设置了 websocket=True，插卡的setting中enablewebsocket=True

**Comment by aboutmydreams** [comment]
谢谢，服务器代理问题应该http up-> websocket

**Comment by aboutmydreams** [comment]
贴一下方案
```
location /{
    proxy_pass http://127.0.0.1:8080;
    # 增加Upgrade协议头和Connection协议头，使http连接升级到websocket连接
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```
