### ISSUE TITLE
400参数错误

### ISSUE THREAD

**Issue by jiangjiangflies** [project-mirai/mirai-api-http#138]
第一步auth认证，一直{"code":400,"msg":"参数格式错误"} 是怎么回事？

**Comment by daofeng2015** [comment]
> 第一步auth认证，一直{"code":400,"msg":"参数格式错误"} 是怎么回事？

你都没日志.都没截图.我那知道你发了啥?

**Comment by ryoii** [comment]
提供各软件版本号

**Comment by tennessine** [comment]
@jiangjiangflies 用postman怎么发送，我post raw json到/verify接口返回

{
    "code": 400,
    "msg": "参数格式错误"
}

**Comment by Yi-pixel** [comment]
> @jiangjiangflies 用postman怎么发送，我post raw json
> 
> ```
> {
>     "verifyKey": "INITKEYxKNtUn5K"
> }
> ```
> 
> 到/verify接口返回
> 
> ```
> {
>     "code": 400,
>     "msg": "参数格式错误"
> }
> ```

## TLDR

刚刚也遇到了这个问题，最终发现，当使用最新 mcl 安装插件后，启动会报错，在 config.json 把所有插件的 channel 改为 stable ，可以正常安装并启用找个插件，但是有个问题，就是这个插件在启动时会报以下错误` [INFO] "net.mamoe:mirai-api-http:2.1.0" is corrupted` ，然后自动下载了 1.10.0 版本，然后成功启动，也就是最终启动的安装实际上是 1.10.0 版本，可以在 config.json 里面看到最终安装的版本，也就是**这时候应该使用 v1 版本的方式使用 /auth 来认证，然后使用 /verify 获取 SessionKey**。

## 安装步骤

### 安装 MCL

```bash
@jack ➜  mirai  .\mcl-installer-1.0.3-windows-amd64.exe
iTXTech MCL Installer 1.0.3 [OS: windows]
Licensed under GNU AGPLv3.
https://github.com/iTXTech/mcl-installer

iTXTech MCL and Java will be downloaded to "D:\2vy\app\mirai"

Checking existing Java installation.
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

Would you like to install Java? (Y/N, default: Y) n
Fetching iTXTech MCL Package Info from https://gitee.com/peratx/mirai-repo/raw/master/org/itxtech/mcl/package.json
Mirai Console Loader 公告栏

[mirai-console] 最近, 项目组发现了权限系统可能会被错误的提前加载导致的3rd权限系统无法正确加载

于是决定, 于 2.6 起, 超前访问权限系统将得到一个错误并中断插件加载, 请各开发者及时检查

影响范围: https://github.com/mamoe/mirai-console/pull/307


The latest stable version of iTXTech MCL is 1.2.1
Would you like to download it? (Y/N, default: Y) y
Start Downloading: https://github.com/iTXTech/mirai-console-loader/releases/download/v1.2.1/mcl-1.2.1.zip
Downloading: 1565250/1565250
Extracting [14/14] scripts/updater.jsjsjs
Use ".\mcl" to start MCL.

Press Enter to exit.
```

### 添加插件

```bash
@jack ➜  mirai  .\mcl --update-package net.mamoe:mirai-api-http --channel stable --type plugin
 12:41:23 [INFO] iTXTech Mirai Console Loader version 1.2.1-de7b624
 12:41:23 [INFO] https://github.com/iTXTech/mirai-console-loader
 12:41:23 [INFO] This program is licensed under GNU AGPL v3
 12:41:23 [INFO] MCL Addon is installed! See https://github.com/iTXTech/mcl-addon
 12:41:23 [INFO] To remove MCL Addon, run "mcl --disable-script addon" and "mcl --remove-package org.itxtech:mcl-addon --delete"
 12:41:23 [INFO] BouncyCastle is installed because OracleJDK is detected.
 12:41:23 [INFO] Package "net.mamoe:mirai-api-http" has been added.
```

### 启动 MCL

```bash
@jack ➜  mirai  .\mcl
 12:41:34 [INFO] iTXTech Mirai Console Loader version 1.2.1-de7b624
 12:41:34 [INFO] https://github.com/iTXTech/mirai-console-loader
 12:41:34 [INFO] This program is licensed under GNU AGPL v3
 12:41:35 [INFO] Fetching Mirai Console Loader Announcement...
 12:41:35 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

[mirai-console] 最近, 项目组发现了权限系统可能会被错误的提前加载导致的3rd权限系统无法正确加载

于是决定, 于 2.6 起, 超前访问权限系统将得到一个错误并中断插件加载, 请各开发者及时检查

影响范围: https://github.com/mamoe/mirai-console/pull/307


 12:41:35 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" version
 12:41:35 [INFO] "org.bouncycastle:bcprov-jdk15on:" is corrupted. Start downloading...
 Downloading bcprov-jdk15on-1.64.jar [==============================] 4.55 MB
 Downloading bcprov-jdk15on-1.64.sha1 [==============================] 40 B
 12:41:40 [INFO] Verifying "net.mamoe:mirai-console" version
 12:41:40 [INFO] "net.mamoe:mirai-console:" is corrupted. Start downloading...
 Downloading mirai-console-2.7-M2.jar [==============================] 3.34 MB
 Downloading mirai-console-2.7-M2.sha1 [==============================] 40 B
 12:41:43 [INFO] Verifying "net.mamoe:mirai-console-terminal" version
 12:41:43 [INFO] "net.mamoe:mirai-console-terminal:" is corrupted. Start downloading...
 Downloading mirai-console-terminal-2.7-M2.jar [==============================] 1.24 MB
 Downloading mirai-console-terminal-2.7-M2.sha1 [==============================] 40 B
 12:41:45 [INFO] Verifying "net.mamoe:mirai-core-all" version
 12:41:45 [INFO] "net.mamoe:mirai-core-all:" is corrupted. Start downloading...
 Downloading mirai-core-all-2.7-M2.jar [==============================] 34.46 MB
 Downloading mirai-core-all-2.7-M2.sha1 [==============================] 40 B
 12:41:52 [INFO] Verifying "org.itxtech:mcl-addon" version
 12:41:52 [INFO] "org.itxtech:mcl-addon:" is corrupted. Start downloading...
 Downloading mcl-addon-1.2.1.jar [==============================] 18.81 KB
 Downloading mcl-addon-1.2.1.sha1 [==============================] 40 B
 12:41:53 [INFO] Verifying "net.mamoe:mirai-api-http" version
 12:41:53 [INFO] "net.mamoe:mirai-api-http:" is corrupted. Start downloading...
 Downloading mirai-api-http-1.10.0.jar [==============================] 4.98 MB
 Downloading mirai-api-http-1.10.0.sha1 [==============================] 40 B
 Downloading mirai-api-http-1.10.0.metadata [==============================] 532 B
 12:41:55 [WARNING] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Current version is 2.7-M2
2021-07-27 12:41:57 I/main: Starting mirai-console...
2021-07-27 12:41:57 I/main: Backend: version 2.7-M2, built on 2021-07-06 21:43:31.
2021-07-27 12:41:57 I/main: Frontend Terminal: version 2.7-M2, provided by Mamoe Technologies
2021-07-27 12:41:57 I/main: Welcome to visit https://mirai.mamoe.net/
2021-07-27 12:41:57 I/plugin: Successfully loaded plugin MCL Addon
2021-07-27 12:41:57 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
2021-07-27 12:41:57 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-07-27 12:41:57 I/MCL Addon: iTXTech MCL Version: 1.2.1-de7b624
2021-07-27 12:41:57 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2021-07-27 12:41:57 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:8080
2021-07-27 12:41:57 I/Mirai HTTP API: Http api server is running with authKey: INITKEYLga9Eo16
2021-07-27 12:41:57 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2021-07-27 12:41:57 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2021-07-27 12:41:57 I/main: 2 plugin(s) enabled.
2021-07-27 12:41:57 I/main: mirai-console started successfully.
2021-07-27 12:41:57 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt:48)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt)
        at io.ktor.features.CORS$Feature.install(CORS.kt:517)
        at io.ktor.features.CORS$Feature.install(CORS.kt:509)
        at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:68)
        at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:45)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:29)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:138)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:270)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

>
```

然后启动会继续，完成后会有 `2021-07-27 12:41:57 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'` 这个错误。

### 修改配置
此时根目录下的 `config.json`

```diff,json5
{
  "js_optimization_level": -1,
  "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
  "maven_repo": [
    "https://maven.aliyun.com/repository/public"
  ],
  "packages": [
    {
      "id": "org.bouncycastle:bcprov-jdk15on",
      "channel": "stable",
      "version": "1.64",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-console",
-      "channel": "beta",
+      "channel": "stable",
      "version": "2.7-M2",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
-      "channel": "beta",
+      "channel": "stable",
      "version": "2.7-M2",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-core-all",
-      "channel": "beta",
+      "channel": "stable",
      "version": "2.7-M2",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "org.itxtech:mcl-addon",
      "channel": "stable",
      "version": "1.2.1",
      "type": "plugins",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-api-http",
      "channel": "stable",
      "version": "1.10.0",
      "type": "plugins",
      "versionLocked": false
    }
  ],
  "disabled_scripts": [],
  "proxy": "",
  "log_level": 1,
  "script_props": {}
}
```

将上述所有 `packages.*.channel` 为 beta 的修改为 stable 后，重新启动，此时如预期一样，启动完成，没有错误。

```bash
@jack ➜  mirai  .\mcl
 12:46:51 [INFO] iTXTech Mirai Console Loader version 1.2.1-de7b624
 12:46:51 [INFO] https://github.com/iTXTech/mirai-console-loader
 12:46:51 [INFO] This program is licensed under GNU AGPL v3
 12:46:51 [INFO] Fetching Mirai Console Loader Announcement...
 12:46:52 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

[mirai-console] 最近, 项目组发现了权限系统可能会被错误的提前加载导致的3rd权限系统无法正确加载

于是决定, 于 2.6 起, 超前访问权限系统将得到一个错误并中断插件加载, 请各开发者及时检查

影响范围: https://github.com/mamoe/mirai-console/pull/307


 12:46:52 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" version 1.64
 12:46:52 [INFO] Verifying "net.mamoe:mirai-console" version 2.7-M2
 Downloading mirai-console-2.6.7.jar [==============================] 3.33 MB
 Downloading mirai-console-2.6.7.sha1 [==============================] 40 B
 12:47:13 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.7-M2
 Downloading mirai-console-terminal-2.6.7.jar [==============================] 1.24 MB
 Downloading mirai-console-terminal-2.6.7.sha1 [==============================] 40 B
 12:47:21 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.7-M2
 Downloading mirai-core-all-2.6.7.jar [==============================] 31.01 MB
 Downloading mirai-core-all-2.6.7.sha1 [==============================] 40 B
 12:50:11 [INFO] Verifying "org.itxtech:mcl-addon" version 1.2.1
 12:50:11 [INFO] Verifying "net.mamoe:mirai-api-http" version 1.10.0
 12:50:11 [WARNING] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Current version is 2.6.7
2021-07-27 12:50:13 I/main: Starting mirai-console...
2021-07-27 12:50:14 I/main: Backend: version 2.6.7, built on 2021-06-19 00:16:08.
2021-07-27 12:50:14 I/main: Frontend Terminal: version 2.7-M2, provided by Mamoe Technologies
2021-07-27 12:50:14 I/main: Welcome to visit https://mirai.mamoe.net/
2021-07-27 12:50:14 I/plugin: Successfully loaded plugin MCL Addon
2021-07-27 12:50:14 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
2021-07-27 12:50:14 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-07-27 12:50:14 I/MCL Addon: iTXTech MCL Version: 1.2.1-de7b624
2021-07-27 12:50:14 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2021-07-27 12:50:14 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:8080
2021-07-27 12:50:14 I/Mirai HTTP API: Http api server is running with authKey: INITKEYLga9Eo16
2021-07-27 12:50:14 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2021-07-27 12:50:14 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2021-07-27 12:50:14 I/main: 2 plugin(s) enabled.
2021-07-27 12:50:14 I/main: mirai-console started successfully.
>
```

此时的 config.json
```json5
{
  "js_optimization_level": -1,
  "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
  "maven_repo": [
    "https://maven.aliyun.com/repository/public"
  ],
  "packages": [
    {
      "id": "org.bouncycastle:bcprov-jdk15on",
      "channel": "stable",
      "version": "1.64",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-console",
      "channel": "stable",
      "version": "2.6.7",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
      "channel": "stable",
      "version": "2.6.7",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-core-all",
      "channel": "stable",
      "version": "2.6.7",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "org.itxtech:mcl-addon",
      "channel": "stable",
      "version": "1.2.1",
      "type": "plugins",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-api-http",
      "channel": "stable",
      "version": "1.10.0",
      "type": "plugins",
      "versionLocked": false
    }
  ],
  "disabled_scripts": [],
  "proxy": "",
  "log_level": 1,
  "script_props": {}
}
```

🤔 其实在最开始， http plugin 就成了 `1.10.0` 版本了，并没有安装最新的 2.1.0，即使修改成 2.1.0 ，启动时仍然会报 `"net.mamoe:mirai-api-http:2.1.0" is corrupted` 然后开始自动安装 1.10.0 。


@ryoii @daofeng2015 不知这是否是一个问题

**Comment by ryoii** [comment]
建议在mcl里开issue，当前版本号比仓库版本号要大时，应该不更新

**Comment by ryoii** [comment]
目前mah没有维持原group的maven仓库权限

**Comment by Yi-pixel** [comment]
> 目前mah没有维持原group的maven仓库权限

看起来是这样，目前 maven 仓库中最新的是 1.10.0（使用 MCL 自动会安装这个版本），但是文档默认已经是 v2 的了，所以容易造成误解，😉 建议通知 `net:mamoe` 更新一下
