### ISSUE TITLE
Plugin在console和console-pure 1.0版本下会启动失败？

### ISSUE THREAD

**Issue by lydrainbowcat** [project-mirai/mirai-api-http#145]
版本：1.7.4，core 1.2.2，console / console-pure 1.0-M2

不带插件能启动，带插件报下面的错误

（用console 0.5.2+console-wrapper可以加载插件……）

所以是我蠢了……还是目前不支持console 1.0以上的版本？（感谢作者

```
java -cp ./lib/* net.mamoe.mirai.console.pure.MiraiConsolePureLoader
2020-08-30 08:01:37 I/main: Starting mirai-console...
2020-08-30 08:01:37 I/main: Backend: version 1.0-M2-1, built on 2020-08-21.
2020-08-30 08:01:37 I/main: Frontend Pure: version 1.0-M2-1.
2020-08-30 08:01:37 I/main: Preparing built-in commands: help, login, stop
2020-08-30 08:01:37 I/main: Loading plugins...
2020-08-30 08:01:38 W/stderr: Exception in thread "main" net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'version' in 'net.mamoe.mirai.console.plugin.jvm.JvmPluginDescriptionImpl'
2020-08-30 08:01:38 W/stderr: version: v1.7.4
2020-08-30 08:01:38 W/stderr:               ^ at line 5, column 16
2020-08-30 08:01:38 W/stderr:
2020-08-30 08:01:38 W/stderr:   at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:170)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.plugin.jvm.JvmPluginDescriptionImpl$$serializer.deserialize(JvmPluginDescriptionImpl.kt)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.plugin.jvm.JvmPluginDescriptionImpl$$serializer.deserialize(JvmPluginDescriptionImpl.kt:38)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:154)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.internal.plugin.JarPluginLoaderImpl.mapToDescription(JarPluginLoaderImpl.kt:67)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.plugin.AbstractFilePluginLoader.listPlugins(PluginLoader.kt:91)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.plugin.jvm.JarPluginLoader$INSTANCE.listPlugins(JarPluginLoader.kt)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.plugin.DeferredPluginLoader.listPlugins(PluginLoader.kt:101)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAllPlugins(PluginManagerImpl.kt:144)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAndEnableLoaderProviders(PluginManagerImpl.kt:131)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadEnablePlugins$mirai_console(PluginManagerImpl.kt:112)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:90)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:90)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.pure.MiraiConsolePureLoaderKt.startup(MiraiConsolePureLoader.kt:45)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:37)
2020-08-30 08:01:38 W/stderr: Caused by: com.vdurmont.semver4j.SemverException: Invalid version (no major version): v1.7.4
2020-08-30 08:01:38 W/stderr:   at com.vdurmont.semver4j.Semver.<init>(Semver.java:61)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.internal.setting.SemverAsStringSerializerLoose$$special$$inlined$map$1.deserialize(serializerUtil.kt:49)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.internal.setting.SemverAsStringSerializerLoose.deserialize(SemverAsStringSerializer.kt)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.mirai.console.internal.setting.SemverAsStringSerializerLoose.deserialize(SemverAsStringSerializer.kt:18)
2020-08-30 08:01:38 W/stderr:   at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
2020-08-30 08:01:38 W/stderr:   ... 14 more
```

**Comment by ryoii** [comment]
console 1.0开始做了大量修改，暂时未做适配

**Comment by ryoii** [comment]
已适配
