### ISSUE TITLE
无法被 mirai-console-1.0-M4 加载

### ISSUE THREAD

**Issue by jinzhijie** [project-mirai/mirai-api-http#163]
目录树：
```
mirai
│  mirai-console-wrapper-0.1.1.jar
│
├─config
│  ├─Console
│  │      AutoLogin.yml
│  │      ExtensionSelector.yml
│  │      PermissionService.yml
│  │
│  └─MiraiAPIHTTP
│          net.mamoe.mirai.api.http.config.Setting.yaml  // 自己手动创建的
│
├─content
│      mirai-console-1.0-M4.jar
│      mirai-console-pure-1.0-M4.jar
│      mirai-core-qqandroid-1.2.3.jar
│
├─data
└─plugins
        mirai-api-http-v1.8.2.jar
```
报错如下：
``` log
2020-09-13 10:49:01 I/main: Starting mirai-console...                                                                                                                   
2020-09-13 10:49:01 I/main: Backend: version 1.0-M4, built on 2020-09-13 02:19:35.                                                                                      
2020-09-13 10:49:01 I/main: Frontend Pure: version 1.0-M4, provided by Mamoe Technologies                                                                               
2020-09-13 10:49:01 V/main: Loading configurations...                                                                                                                   
2020-09-13 10:49:02 V/main: Loading JVM plugins...                                                                                                                      
mirai-console broken!                                                                                                                                                   
java.lang.reflect.InvocationTargetException                                                                                                                             
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                  
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)                                                                                                  
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)                                                                                              
        at java.lang.reflect.Method.invoke(Unknown Source)                                                                                                              
        at pw.konge.mirai.console.wrapper.Wrapper.main(Wrapper.java:80)                                                                                                 
Caused by: net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service net.mamoe.mirai.api.http.HttpApiPluginBase.                               
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:56)                                                             
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(PluginServiceHelper.kt:38)                                                         
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$1$1.invoke(BuiltInJvmPluginLoaderImpl.kt:62)                               
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$1$1.invoke(BuiltInJvmPluginLoaderImpl.kt:29)                               
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)                                                                                      
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)                                                                          
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)                                                                                     
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)                                                                                   
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)                                                                                   
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:316)                                                                          
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)                                                                                     
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:742)                                                                                   
        at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:783)                                                                                          
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:80)                                          
        at net.mamoe.mirai.console.plugin.loader.AbstractFilePluginLoader.listPlugins(FilePluginLoader.kt:42)                                                           
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)                                                                   
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:182)                                                    
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:126)                                 
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:136)                          
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:133)                             
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:184)                                                        
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:150)                                                             
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:149)                                                     
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:46)                                                                       
        ... 5 more                                                                                                                                                      
Caused by: java.lang.NoClassDefFoundError: net/mamoe/mirai/console/plugin/description/PluginKind                                                                        
        at net.mamoe.mirai.api.http.HttpApiPluginDescription.<clinit>(HttpApiPluginDescription.kt:12)                                                                   
        at net.mamoe.mirai.api.http.HttpApiPluginBase.<init>(HttpApiPluginBase.kt:27)                                                                                   
        at net.mamoe.mirai.api.http.HttpApiPluginBase.<clinit>(HttpApiPluginBase.kt:27)                                                                                 
        at java.lang.Class.forName0(Native Method)                                                                                                                      
        at java.lang.Class.forName(Unknown Source)                                                                                                                      
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:47)                                                             
        ... 28 more                                                                                                                                                     
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.console.plugin.description.PluginKind                                                                      
        at java.net.URLClassLoader.findClass(Unknown Source)                                                                                                            
        at java.lang.ClassLoader.loadClass(Unknown Source)                                                                                                              
        at java.lang.ClassLoader.loadClass(Unknown Source)                                                                                                              
        ... 34 more                                                                                                                                                     
```

**Comment by HoshinoTented** [comment]
目前还没适配，使用的版本是 1.0-M4-dev-3

**Comment by jinzhijie** [comment]
> 目前还没适配，使用的版本是 1.0-M4-dev-3

:thinking: 那 mirai-repo 里那个 M4 的是 smjb。。。

**Comment by HoshinoTented** [comment]
当时适配的时候还没出 M4

**Comment by jinzhijie** [comment]
那估计过多久能支持 M4？ :smiley:

**Comment by Hieuzest** [comment]
> 那估计过多久能支持 M4？ 😃

你可以从Actions中下载已经支持M4的pr版本

**Comment by jinzhijie** [comment]
> > 那估计过多久能支持 M4？ smiley
> 
> 你可以从Actions中下载已经支持M4的pr版本

找到力，thx。我可以 close 了么

**Comment by HoshinoTented** [comment]
已适配 M4，建议 close
