### ISSUE TITLE
插件导致Console关闭时报错

### ISSUE THREAD

**Issue by KawaiiZapic** [project-mirai/mirai-api-http#167]
```
Stopping mirai-console
2020-09-15 01:08:51 E/main: Exception in stop
kotlinx.coroutines.CompletionHandlerException: Exception in completion handler ChildHandle[SupervisorJobImpl{Cancelling}@477feabf] for SupervisorJobImpl{Cancelling}@115e78e4
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1516)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:897)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:693)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:664)
        at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:629)
        at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:614)
        at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:192)
        at kotlinx.coroutines.JobKt__JobKt.cancelAndJoin(Job.kt:510)
        at kotlinx.coroutines.JobKt.cancelAndJoin(Unknown Source)
        at net.mamoe.mirai.console.command.BuiltInCommands$StopCommand.handle(BuiltInCommands.kt:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.full.KCallables.callSuspend(KCallables.kt:55)
        at net.mamoe.mirai.console.internal.command.CompositeCommandInternalKt$createSubCommand$7.invokeSuspend(CompositeCommandInternal.kt:334)
        at net.mamoe.mirai.console.internal.command.CompositeCommandInternalKt$createSubCommand$7.invoke(CompositeCommandInternal.kt)
        at net.mamoe.mirai.console.internal.command.AbstractReflectionCommand$SubCommandDescriptor.parseAndExecute$mirai_console(CompositeCommandInternal.kt:148)
        at net.mamoe.mirai.console.command.SimpleCommand.onCommand(SimpleCommand.kt:77)
        at net.mamoe.mirai.console.internal.command.ExecuteCommandInternalKt.executeCommandInternal(executeCommandInternal.kt:64)
        at net.mamoe.mirai.console.internal.command.ExecuteCommandInternalKt.executeCommandInternal(executeCommandInternal.kt:61)
        at net.mamoe.mirai.console.internal.command.CommandManagerImpl.executeCommand(CommandManagerImpl.kt:184)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt:175)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:123)
        at net.mamoe.mirai.console.pure.ConsoleThreadKt$startupConsoleThread$1.invokeSuspend(ConsoleThread.kt:49)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: kotlinx.coroutines.CompletionHandlerException: Exception in completion handler ChildHandle[SupervisorJobImpl{Cancelled}@3100f452] for SupervisorJobImpl{Cancelling}@477feabf
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1516)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:897)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:693)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:664)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:634)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1473)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1511)
        ... 34 more
Caused by: kotlinx.coroutines.CompletionHandlerException: Exception in completion handler InvokeOnCompletion[InvokeOnCompletion@23b533dc] for SupervisorJobImpl{Cancelled}@3100f452
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1536)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:693)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:664)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:634)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1473)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1511)
        ... 41 more
Caused by: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@115e78e4
Exception in completion handler ChildHandle[SupervisorJobImpl{Cancelling}@477feabf] for SupervisorJobImpl{Cancelling}@115e78e4
```

**Comment by HoshinoTented** [comment]
从哪里看出是 mirai-api-http 导致的报错？

**Comment by KawaiiZapic** [comment]
> 从哪里看出是 mirai-api-http 导致的报错？

仅安装插件并关闭console就会有此报错,不安装任何插件就无此报错.  
同时这可能也暴露出console可能对异常处理不够完善的问题,但是证据貌似不大足.

**Comment by HoshinoTented** [comment]
安装 mirai-console-example-plugin 关闭 console 不报错，看起来 mah 的确有一定的问题

**Comment by HoshinoTented** [comment]
console 已修
