### ISSUE TITLE
上传图片和语音文件均报错 java.io.IOException

### ISSUE THREAD

**Issue by vivien8261** [project-mirai/mirai-api-http#170]
2020-09-16 14:20:14 E/MiraiApiHttp: java.io.IOException: 拒绝访问。
java.io.IOException: �ܾ����ʡ�
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at io.ktor.http.cio.CIOMultipartDataBase.partToData(CIOMultipartData.kt:99)
        at io.ktor.http.cio.CIOMultipartDataBase$partToData$1.invokeSuspend(CIOMultipartData.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by vivien8261** [comment]
版本1.8.3，之前用1.7没有这个问题，可能是要访问哪个文件夹没有权限导致的？

**Comment by vivien8261** [comment]
在本地运行会出现这个错误，但在服务器没有重现……close了
