### ISSUE TITLE
python mirai 无法连接到 mirai-api-http

### ISSUE THREAD

**Issue by unhumanplane** [project-mirai/mirai-api-http#173]
21:16:41 [ERROR] [MiraiAPIHTTP] java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.api.http.util.MiraiJson
        at net.mamoe.mirai.api.http.route.AuthRouteModuleKt$authModule$1$$special$$inlined$miraiAuth$1$1.invokeSuspend(BaseRoute.kt:341)
        at net.mamoe.mirai.api.http.route.AuthRouteModuleKt$authModule$1$$special$$inlined$miraiAuth$1$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:188)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:31)
        at io.ktor.routing.Routing.executeResult(Routing.kt:147)
        at io.ktor.routing.Routing.interceptor(Routing.kt:34)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:188)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:31)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:120)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:323)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:168)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:188)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:31)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:167)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 21:16:46 [ERROR] [MiraiAPIHTTP] java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.api.http.util.MiraiJson
        at net.mamoe.mirai.api.http.route.AuthRouteModuleKt$authModule$1$$special$$inlined$miraiAuth$1$1.invokeSuspend(BaseRoute.kt:341)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

core：1.3.0 console:0.5.2 http-api:1.7.4
可能是已经不兼容很久没更新的pythonapi了？

**Comment by Hieuzest** [comment]
请使用console:0.5.2+http:1.8.0-pre或console:1.0-M4+http:1.8.3
http:1.7最高支持到core:1.1.3

**Comment by GreyElaina** [comment]
?

**Comment by HoshinoTented** [comment]
?

**Comment by Karlatemp** [comment]
？

**Comment by ryoii** [comment]
那 issue 发到这里并没有用啊

**Comment by unhumanplane** [comment]
> 请使用console:0.5.2+http:1.8.0-pre或console:1.0-M4+http:1.8.3
> http:1.7最高支持到core:1.1.3

感谢，改成1.8.0-pre就可以了
