### ISSUE TITLE
结束时一大串报错什么鬼？？

### ISSUE THREAD

**Issue by zhzRedstone** [project-mirai/mirai-api-http#185]
```
2020-10-01 20:05:14 I/MiraiOK: MiraiOK 20200915.071520 windows-amd64
2020-10-01 20:05:14 I/MiraiOK: 此程序以Affero GPL3.0协议发布，使用时请遵守协议
2020-10-01 20:05:14 I/MiraiOK: 部分开源于: github.com/LXY1226/MiraiOK
2020-10-01 20:05:14 I/MiraiOK: java version "11.0.8" 2020-07-14 LTS
2020-10-01 20:05:14 I/MiraiOK: Java(TM) SE Runtime Environment 18.9 (build 11.0.
8+10-LTS)
2020-10-01 20:05:14 I/MiraiOK: Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.
0.8+10-LTS, mixed mode)
2020-10-01 20:05:14 I/MiraiOK: 删除.lastupdate来在下次启动时强制检查更新
2020-10-01 20:05:14 I/MiraiOK: 启动Mirai...
2020-10-01 20:05:15 I/main: Starting mirai-console...
2020-10-01 20:05:15 I/main: Backend: version 1.0-M4, built on 2020-09-13 02:19:3
5.
2020-10-01 20:05:15 I/main: Frontend Pure: version 1.0-M4, provided by Mamoe Tec
hnologies
2020-10-01 20:05:15 V/main: Loading configurations...
2020-10-01 20:05:16 V/main: Loading JVM plugins...
2020-10-01 20:05:16 I/plugin: Successfully loaded plugin MiraiApiHttp
2020-10-01 20:05:16 V/main: 0 external PluginLoader(s) found.
2020-10-01 20:05:16 V/main: 1 plugin(s) loaded.
2020-10-01 20:05:16 V/main: Loading PermissionService...
2020-10-01 20:05:16 V/main: Reloaded PermissionService settings.
2020-10-01 20:05:16 V/main: Loading built-in commands...
2020-10-01 20:05:16 V/main: Prepared built-in commands: help, login, permission,
 stop
2020-10-01 20:05:16 V/main: Enabling plugins...
2020-10-01 20:05:17 I/MiraiApiHttp: Starting Mirai HTTP Server in 0.0.0.0:5710
2020-10-01 20:05:17 I/MiraiApiHttp: Starting Mirai HTTP Server in 0.0.0.0:5710
2020-10-01 20:05:17 I/Mirai HTTP API: Http api server is running with authKey: 3
173857429
2020-10-01 20:05:17 I/MiraiApiHttp: 心跳模块启用状态: true
2020-10-01 20:05:17 I/MiraiApiHttp: 上报模块启用状态: true
2020-10-01 20:05:17 I/main: 1 plugin(s) enabled.
2020-10-01 20:05:17 I/main: Auto-login 3173857429
2020-10-01 20:05:19 I/Bot 3173857429: Logging in...
2020-10-01 20:05:21 V/Bot 3173857429: Event: MessageSvcPbGetMsg.Response(syncFla
gFromServer=CONTINUE, messages=<Iterable>))
2020-10-01 20:05:21 V/Bot 3173857429: Event: MessageSvcPbGetMsg.Response(syncFla
gFromServer=CONTINUE, messages=<Iterable>))
2020-10-01 20:05:22 V/Bot 3173857429: Event: MessageSvcPbGetMsg.Response(syncFla
gFromServer=CONTINUE, messages=<Iterable>))
2020-10-01 20:05:22 I/Bot 3173857429: Login successful
2020-10-01 20:05:22 I/main: mirai-console started successfully.
2020-10-01 20:05:23 V/Bot 3173857429: [V家(608553250)] 仙阿茶☁️怒吼 啊啊啊啊啊啊
(3279180856) -> [mirai:source:983305,2013937387]还是其他的什么鬼
2020-10-01 20:05:28 V/Bot 3173857429: [MineCraft(708651154)] youyang(2521376597)
 -> [mirai:source:17395,1448171647]50倍也就这样了
>
2020-10-01 20:05:30 E/main: Exception in coroutine Input
kotlinx.coroutines.CompletionHandlerException: Exception in completion handler C
hildHandle[SupervisorJobImpl{Cancelling}@6bbec484] for SupervisorJobImpl{Cancell
ing}@5b6da314
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1516)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt
:897)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:693)

        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobS
upport.kt:664)
        at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:629)
        at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:614)
        at kotlinx.coroutines.CoroutineScopeKt.cancel(CoroutineScope.kt:217)
        at kotlinx.coroutines.CoroutineScopeKt.cancel$default(CoroutineScope.kt:
215)
        at net.mamoe.mirai.console.pure.ConsoleThreadKt$startupConsoleThread$1.i
nvokeSuspend(ConsoleThread.kt:68)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:665)
Caused by: kotlinx.coroutines.CompletionHandlerException: Exception in completio
n handler ChildHandle[SupervisorJobImpl{Cancelled}@1280a0e6] for SupervisorJobIm
pl{Cancelling}@6bbec484
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1516)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt
:897)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:693)

        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobS
upport.kt:664)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:634)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1473)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1511)
        ... 15 more
Caused by: kotlinx.coroutines.CompletionHandlerException: Exception in completio
n handler InvokeOnCompletion[InvokeOnCompletion@8ebe642] for SupervisorJobImpl{C
ancelled}@1280a0e6
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1536)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt
:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:24
0)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt
:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:693)

        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobS
upport.kt:664)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:634)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1473)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1511)
        ... 22 more
Caused by: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=S
upervisorJobImpl{Cancelling}@5b6da314
2020-10-01 20:05:33 I/Bot 3173857429: Bot cancelled: Job was cancelled


```

**Comment by zhzRedstone** [comment]
已知bug（），先close了
