### ISSUE TITLE
mirai-console-loader 无法加载 mirai-api-http 插件

### ISSUE THREAD

**Issue by Steve-xmh** [project-mirai/mirai-api-http#192]
不知道是不是我的配置还是版本的问题，想请教一下

按照官方文档的方式下载了 mah 并放好了 readme 的默认配置，启动时加载插件时报错退出。

使用的库及版本：
- mirai-console-loader-1.0.0.jar
- mirai-console-1.0-M4.jar
- mirai-console-1.0-RC-dev-29.jar
- mirai-console-terminal-1.0-RC-dev-29.jar
- mirai-core-all-1.3.1.jar

```
> java -jar .\mirai-console-loader-1.0.0.jar
 10:28:37 [INFO] Mirai Console Loader version 1.0.0-f27aff0
 10:28:37 [INFO] https://github.com/iTXTech/mirai-console-loader
 10:28:37 [INFO] This program is licensed under GNU AGPL v3
 10:28:37 [DEBUG] Loading script: boot.js
 10:28:37 [DEBUG] Loading script: config.js
 10:28:38 [DEBUG] Loading script: updater.js
 10:28:38 [INFO] Verifying "net.mamoe:mirai-console" version 1.0-RC-dev-29
 10:28:39 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 1.0-RC-dev-29
 10:28:39 [INFO] Verifying "net.mamoe:mirai-core-all" version 1.3.1
2020-10-08 10:28:41 I/main: Starting mirai-console...
2020-10-08 10:28:41 I/main: Backend: version 1.0-RC-dev-28, built on 2020-09-21 12:37:02.
2020-10-08 10:28:41 I/main: Frontend Terminal: version 1.0-RC-dev-28, provided by Mamoe Technologies
2020-10-08 10:28:41 V/main: Loading configurations...
2020-10-08 10:28:42 V/main: Loading JVM plugins...
 10:28:42 [ERROR] org.mozilla.javascript.WrappedException: Wrapped net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service net.mamoe.mirai.api.http.HttpApiPluginBase. (boot.js#70)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at script(boot.js:70)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.InterfaceAdapter$$Lambda$15/0000000000000000.run(Unknown Source)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:127)
        at org.itxtech.mcl.Loader.main(Loader.java:54)
Caused by: net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service net.mamoe.mirai.api.http.HttpApiPluginBase.
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:56)
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(PluginServiceHelper.kt:38)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$1$1.invoke(BuiltInJvmPluginLoaderImpl.kt:62)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$1$1.invoke(BuiltInJvmPluginLoaderImpl.kt:29)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:316)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:742)
        at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:783)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:80)
        at net.mamoe.mirai.console.plugin.loader.AbstractFilePluginLoader.listPlugins(FilePluginLoader.kt:42)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:183)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:127)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:137)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:132)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:194)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:82)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        ... 19 more
Caused by: java.lang.NoSuchMethodError: net/mamoe/mirai/console/plugin/jvm/JvmPluginDescription$Companion.invoke$default(Lnet/mamoe/mirai/console/plugin/jvm/JvmPluginDescription$Companion;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lnet/mamoe/mirai/console/plugin/jvm/JvmPluginDescription; (loaded from file:/D:/Programs/kotlin/mirai-console/libs/mirai-console-1.0-RC-dev-29.jar by java.net.URLClassLoader@97e4a5a) called from class net.mamoe.mirai.api.http.HttpApiPluginBase (loaded from file:/D:/Programs/kotlin/mirai-console/./plugins/mirai-api-http-v1.8.4.jar by java.net.URLClassLoader@64a4d931).
        at net.mamoe.mirai.api.http.HttpApiPluginBase.<init>(HttpApiPluginBase.kt:28)
        at net.mamoe.mirai.api.http.HttpApiPluginBase.<clinit>(HttpApiPluginBase.kt:27)
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:47)
        ... 52 more
```

**Comment by Steve-xmh** [comment]
解决了，是 mirai-console-loader 的问题，换成以下库之后手动启动就没有问题了：
- mirai-console-1.0-M4.jar
- mirai-console-1.0-RC-dev-29.jar
- mirai-console-pure-1.0-M4-all.jar
- mirai-core-all-1.3.1.jar
