### ISSUE TITLE
mah成功载入但无法识别setting (Receiver class does not define)

### ISSUE THREAD

**Issue by Eclipzers** [project-mirai/mirai-api-http#200]
`mirai-console-1.0-M4` 能够正常启动
`mirai-api-http-v1.8.4.jar`和`mirai-api-http-v1.8.3.jar`两个都试了
`setting.yml`路径为`config/MiraiApiHttp/setting.yml`
名字试过setting.yml, setting.yaml, 以及 net.mamoe.mirai.api.http.config.Setting.yaml
setting内容完全照抄readme中提供的模板
JDK11.0.8

以上所有尝试反馈都如下：
```
2020-10-27 04:12:19 I/main: Starting mirai-console...
2020-10-27 04:12:19 I/main: Backend: version 1.0-RC-dev-28, built on 2020-09-20 01:40:12.
2020-10-27 04:12:19 I/main: Frontend Terminal: version 1.0-RC-dev-28, provided by Mamoe Technologies
2020-10-27 04:12:19 V/main: Loading configurations...
2020-10-27 04:12:19 V/main: Loading JVM plugins...
2020-10-27 04:12:19 I/plugin: Successfully loaded plugin MiraiApiHttp
2020-10-27 04:12:19 V/main: 0 external PluginLoader(s) found.
2020-10-27 04:12:19 V/main: 1 plugin(s) loaded.
2020-10-27 04:12:19 V/main: Loading PermissionService...
2020-10-27 04:12:19 V/main: Reloaded PermissionService settings.
2020-10-27 04:12:19 V/main: Loading built-in commands...
2020-10-27 04:12:19 V/main: Prepared built-in commands: help, login, permission, stop
2020-10-27 04:12:19 V/main: Enabling plugins...
2020-10-27 04:12:19 E/MiraiApiHttp: java.lang.AbstractMethodError: Receiver class net.mamoe.mirai.api.http.config.Setting does not define or inherit an implementation of the resolved method abstract getSaveName()Ljava/lang/String; of interface net.mamoe.mirai.console.data.PluginData.
java.lang.AbstractMethodError: Receiver class net.mamoe.mirai.api.http.config.Setting does not define or inherit an implementation of the resolved method abstract getSaveName()Ljava/lang/String; of interface net.mamoe.mirai.console.data.PluginData.
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.getPluginDataFile(MultiFilePluginDataStorageImpl.kt:46)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConfig(AbstractJvmPlugin.kt:56)
        at net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:37)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:100)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:168)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:191)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:194)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:49)

2020-10-27 04:12:19 I/main: 1 plugin(s) enabled.
2020-10-27 04:12:19 I/main: mirai-console started successfully.
```
因为翻了过去的记录并没有发现类似问题的解决方案，自己也无法解决，所以在这里提问，希望能得到指点，谢谢。

**Comment by Karlatemp** [comment]
`mirai-api-http` not supported **dev** version now.

**Comment by Eclipzers** [comment]
谢谢回答，请问：
mah的release里1.8.3中说明`更新 console 依赖到 1.0-M4`，并且我在翻查其他人的提问时，别人得到的答复也是“用console1.0-M4和最新的mah”，我所下载的console也是能找到的唯一标着1.0-M4的包，为什么忽然就变成dev version了？

**Comment by Eclipzers** [comment]
根据你的回答我已经找到问题，非常感谢。在按照mirai-console指示，从mirai-repo错误下载了dev版本的jar，现在重新下载了正确版本之后成功启动了。
