### ISSUE TITLE
新增状态码：临时会话关闭

### ISSUE THREAD

**Issue by fuhaixiao** [project-mirai/mirai-api-http#201]
2020-10-30 23:22:24 E/MiraiApiHttp: java.lang.IllegalStateException: Send temp message failed: MessageSvcPbSendMsg.Response.Failed(resultType=103, errorCode=0, errorMessage=发送失败，群主已禁止群成员发起临时会话)
java.lang.IllegalStateException: Send temp message failed: MessageSvcPbSendMsg.Response.Failed(resultType=103, errorCode=0, errorMessage=发送失败，群主已禁止群成员发起临时会话)
	at net.mamoe.mirai.qqandroid.contact.MemberImpl.sendMessageImpl(MemberImpl.kt:94)
	at net.mamoe.mirai.qqandroid.contact.MemberImpl$sendMessageImpl$1.invokeSuspend(MemberImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)

**Comment by ryoii** [comment]
群主已禁止群成员发起临时会话
Chat room owner has forbidden members from initiating temporary chat
チャットルームの所有者は一時的なチャットを開始することからメンバーを禁止している
Le propriétaire du Forum interdit aux membres de lancer des conversations temporaires.
채 팅 방 소유자, 멤버 임시 채 팅 금지
владелец чата запретил участникам открывать временный разговор
