### ISSUE TITLE
插件启动问题

### ISSUE THREAD

**Issue by Chika99** [project-mirai/mirai-api-http#205]
控制台日志
2020-11-02 21:48:56 E/MiraiApiHttp: java.lang.AbstractMethodError: Receiver class net.mamoe.mirai.api.http.config.Setting does not define or inherit an implementation of the resolved method abstract getSaveName()Ljava/lang/String; of interface net.mamoe.mirai.console.data.PluginData.
java.lang.AbstractMethodError: Receiver class net.mamoe.mirai.api.http.config.Setting does not define or inherit an implementation of the resolved method abstract getSaveName()Ljava/lang/String; of interface net.mamoe.mirai.console.data.PluginData.
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.getPluginDataFile(MultiFilePluginDataStorageImpl.kt:46)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConfig(AbstractJvmPlugin.kt:56)
        at net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:37)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:100)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:168)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:191)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:194)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:49)
第一次使用，请问部署时哪里出了问题

**Comment by YukiRus** [comment]
console-RC1版本更新了很多东西但是HTTPAPI没有更新，所以请退回到mirai-core-qqandroid-1.2.3以及mirai-console-1.0-M4

**Comment by ryoii** [comment]
目前版本插件支持到mirai-console-1.0-M4，请使用对于版本。mirai-console 近期存在大量的新功能和特性上的更新，mirai-api-http 会在 mirai-console 发布正式版后再进行适配
