### ISSUE TITLE
使用 url 发送图片文件报 java.io.IOException 

### ISSUE THREAD

**Issue by Excaive** [project-mirai/mirai-api-http#212]
使用 MiraiOK 20200915.071520 windows-386 、 mirai-api-http-v1.8.4.jar ，console为 1.0-M4 

messageChain为
`[{"type": "Image", "url": "https://i0.hdslb.com/bfs/album/67fc4e6b417d9c68ef98ba71d5e79505bbad97a1.png"}]`

用 sendFriendMessage 和 sendGroupMessage 发送消息均报错

```
2020-11-11 23:43:46 E/MiraiApiHttp: java.io.IOException: 拒绝访问。
java.io.IOException: �ܾ����ʡ�
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at kotlin.io.FilesKt__UtilsKt.createTempFile(Utils.kt:59)
        at kotlin.io.FilesKt__UtilsKt.createTempFile$default(Utils.kt:58)
        at net.mamoe.mirai.utils.FileCacheStrategy$TempCache.newImageCache(FileCacheStrategy.jvm.kt:138)
        at net.mamoe.mirai.utils.FileCacheStrategy$PlatformDefault.newImageCache(FileCacheStrategy.jvm.kt)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput$init$3.invokeSuspend(DeferredReusableInput.jvm.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by ryoii** [comment]
这个 `mirai core` 的异常

原因是临时文件所在的目录没有写入权限

**Comment by Excaive** [comment]
请问临时文件目录是 data/MiraiApiHttp/images 吗？
我对该目录的权限进行了调整，但仍然无法解决这一问题

**Comment by ryoii** [comment]
也有可能是plugins/MiraiAPIHTTP/images，console 版本不同似乎不同，我也没有进行详细测试不同 console 版本的行为

**Comment by Excaive** [comment]
目前还是没有解决
此外我注意到，在使用 uploadImage 上传图片时，当图片大小超过某个值（约 8 KB）时，会发生 <Response 500> ；小于这个值则可以成功上传和发送，这时候 data/MiraiApiHttp/images 下会产生一个 img 文件。那么应该是有写入权限的吧

**Comment by Karlatemp** [comment]
遇到的好几个issue的拒绝访问中全是使用MiraiOK的, `java.io.File.createTempFile` 使用的是系统 `TEMP`/`TMP` 路径,
根据查找到的资料以及其他 issue 的详细信息辅助, 得到使用 MiraiOK 的文件临时目录被重定向至 `C:\Windows\SYSTEM32` (@see https://stackoverflow.com/a/55522677), 
由此可以推出 MiraiOK 意外的清空了文件执行的环境变量, 根本解决方法是不使用 MiraiOK

**Comment by Excaive** [comment]
改用手动启动 console ，现在可以使用 url 发送图片了
感谢二位的解答
