### ISSUE TITLE
/command/register 不兼容Console 1.0-RC-1

### ISSUE THREAD

**Issue by KawaiiZapic** [project-mirai/mirai-api-http#214]
版本:
`v1.8.4`  #194 构建
环境:
```
mirai-console-1.0-RC-1
mirai-core-all-1.3.1
mirai-console-terminal-1.0-RC-1
```

请求样例:
```
POST /command/register
{
	"authKey" => {authKey},
	"name" => "lcmd",
	"alias" => [],
	"description" => "",
	"usage" => ""
}
```

控制台输出:
```
E/MiraiApiHttp: java.lang.NoSuchMethodError: net.mamoe.mirai.console.command.RawCommand.<init>(Lnet/mamoe/mirai/console/command/CommandOwner;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lnet/mamoe/mirai/console/permission/Permission;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V
java.lang.NoSuchMethodError: net.mamoe.mirai.console.command.RawCommand.<init>(Lnet/mamoe/mirai/console/command/CommandOwner;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lnet/mamoe/mirai/console/permission/Permission;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V
	at net.mamoe.mirai.api.http.command.RegisterCommand.<init>(RegisterCommand.kt:12)
	at net.mamoe.mirai.api.http.route.CommandRouteModuleKt$commandModule$1$$special$$inlined$miraiAuth$1$1.invokeSuspend(BaseRoute.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by ryoii** [comment]
`mirai-api-http` 当前版本 `1.8.4` 仅支持到 `mirai-console 1.0-M4`

留意 [release](https://github.com/project-mirai/mirai-api-http/releases) 页面可以快速获取版本信息
