### ISSUE TITLE
发送带图片的好友消息失败

### ISSUE THREAD

**Issue by monokuma233** [project-mirai/mirai-api-http#218]
发送带图片的好友消息失败：
2020-11-26 13:09:30 E/MiraiApiHttp: java.lang.IllegalStateException: Send friend message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
java.lang.IllegalStateException: Send friend message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
        at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:64)
        at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

使用版本如下：
mirai-api-http-v1.8.4.jar
mirai-console-1.0-M4.jar
mirai-console-pure-1.0-M4.jar
mirai-core-qqandroid-1.2.3.jar

**Comment by monokuma233** [comment]
消息格式问题，已解决。

**Comment by monokuma233** [comment]
排除了请求端的错误，目前的情况是图片已经传输到mirai端，在/data/MiraiApiHttp/images能找到文件，但是调用发送消息接口还是报错：
2020-11-27 10:02:59 E/MiraiApiHttp: java.lang.IllegalStateException: Send friend message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
java.lang.IllegalStateException: Send friend message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
        at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:64)
        at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by drsanwujiang** [comment]
同样遇到了，不过我这边是发送图片文字和纯文字都有报错现象。可能是风控问题吗？

2020-12-02 23:42:27 E/MiraiApiHttp: java.lang.IllegalStateException: Send friend message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
java.lang.IllegalStateException: Send friend message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
	at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:64)
	at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by ryoii** [comment]
好友消息文字带图可能形成长消息，好友消息目前不支持长消息。留意 core 2.0 的更新

**Comment by drsanwujiang** [comment]
> 好友消息文字带图可能形成长消息，好友消息目前不支持长消息。留意 core 2.0 的更新

那有什么用来规避长消息的指标吗，比如最大字符长度？

**Comment by ryoii** [comment]
分开发送
