### ISSUE TITLE
同时发送多张图片报错

### ISSUE THREAD

**Issue by SAGIRI-kawaii** [project-mirai/mirai-api-http#220]
短时间内同时发送多张图片（如10pics/s）时会出现如下报错
```
 23:04:56 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: cannot upload group image, failed on all servers.
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImageToServers(HighwayHelper.kt:110)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImageToServers$2.invokeSuspend(HighwayHelper.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.flow.internal.SafeCollector.invokeSuspend(SafeCollector.kt:37)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalStateException: highway transfer failed, error 81
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImage$$inlined$use$lambda$1.emit(Collect.kt:149)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImage$$inlined$use$lambda$1$1.invokeSuspend(Unknown Source)
        ... 6 more
```

**Comment by ryoii** [comment]
带宽占满导致部分图片超时

**Comment by I-love-study** [comment]
个人认为并不是宽带满占导致的问题
在#221的条件下
相比于发生发送图片变成同一个
更多情况是其中一个发送失败
(当时看到有这个issue就没提)

**Comment by ryoii** [comment]
从错误是上看包已经发到服务器了，返回的异常状态，这个你只能问腾讯了
