### ISSUE TITLE
python启动时报错

### ISSUE THREAD

**Issue by dixiatielu** [project-mirai/mirai-api-http#237]
无法运行文档中的示例`bot.py`文件
报错如下
```
[root@VM-0-8-centos pyqq]# python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 2, in <module>
    from graia.application import GraiaMiraiApplication, Session
  File "/usr/local/lib/python3.6/site-packages/graia/application/__init__.py", line 7, in <module>
    from contextlib import asynccontextmanager
ImportError: cannot import name 'asynccontextmanager'
```

**Comment by ryoii** [comment]
哪个库的问题你开到哪个库的 `issue`
