### ISSUE TITLE
关于请求400的问题难以session握手

### ISSUE THREAD

**Issue by PluginsKers** [project-mirai/mirai-api-http#245]
这是我发送了的请求：
`curl --data-urlencode 'authKey=12345678' -X POST http://exmple.com:400/auth `
这是返回：
`{"code":400,"msg":"参数格式错误"}`

检查服务端`authKey`

setting.yml
```yml
...
authKey: 12345678
...
```

在启动Bot时Log显示：
```shell
2021-01-26 18:39:16 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:400
2021-01-26 18:39:16 I/Mirai HTTP API: Http api server is running with authKey: 12345678
```

我已经没办法继续排错下去。

**Comment by ryoii** [comment]
`curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"authKey":"12345678"}'  http://exmple.com:400/auth `

**Comment by PluginsKers** [comment]
> `curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"authKey":"12345678"}' http://exmple.com:400/auth `
依旧。

**Comment by PluginsKers** [comment]
这和Linux系统有关系吗？我的防火墙都是开放的。

**Comment by PluginsKers** [comment]
```
^[[0m2021-01-26 23:34:27 V/Net 2167655605: Send: MessageSvc.PbDeleteMsg^[[0m
^[[0m2021-01-26 23:34:27 V/Net 2167655605: Send: MessageSvc.PbGetMsg^[[0m
^[[0m2021-01-26 23:34:27 V/Net 2167655605: Send: MessageSvc.PbDeleteMsg^[[0m
^[[92m2021-01-26 23:34:27 I/Net 2167655605: Syncing friend message history: Success.^[[0m
^[[96m2021-01-26 23:34:29 D/Net 2167655605: Received unknown commandName: ConfigPushSvc.PushDomain^[[0m
^[[0m2021-01-26 23:34:29 V/Net 2167655605: Recv: ConfigPushSvc.PushReq.PushReqResponse.Success^[[0m
^[[0m2021-01-26 23:34:29 V/Net 2167655605: Send: ConfigPushSvc.PushResp^[[0m
^[[92m2021-01-26 23:34:29 I/Net 2167655605: ConfigPushSvc.PushReq: Success.^[[0m
^[[92m2021-01-26 23:37:00 I/Net 2167655605: Connected to server 114.221.144.215:80^[[0m
^[[0m2021-01-26 23:37:00 V/Net 2167655605: Send: wtlogin.login^[[0m
^[[0m2021-01-26 23:37:00 V/Net 2167655605: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin^[[0m
^[[0m2021-01-26 23:37:00 V/Net 2167655605: Send: wtlogin.login^[[0m
^[[0m2021-01-26 23:37:00 V/Net 2167655605: Recv: LoginPacketResponse.Success^[[0m
^[[92m2021-01-26 23:37:00 I/Net 2167655605: Login successful^[[0m
^[[0m2021-01-26 23:37:00 V/Net 2167655605: Send: StatSvc.register^[[0m
^[[0m2021-01-26 23:37:00 V/Net 2167655605: Recv: Response(StatSvc.register)^[[0m
^[[0m2021-01-26 23:37:00 V/Net 2167655605: Send: StatSvc.GetDevLoginInfo^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=1)^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Start loading friend list...^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Start syncing group config...^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Start loading stranger list...^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Send: friendlist.getFriendGroupList^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Send: OidbSvc.0x496^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Send: OidbSvc.0x5d2_0^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Recv: network.protocol.packet.list.StrangerList$GetStrangerList$Response@90e3b21^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Successfully loaded stranger list: 0 in total^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Recv: TroopManagement.GetTroopConfig.Response(true)^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Successfully synced group config.^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Start loading group list...^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Send: friendlist.GetTroopListReqV2^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Recv: FriendList.GetFriendGroupList.Response^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Loading friend list: 3/3^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Successfully loaded friend list: 3 in total^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Recv: FriendList.GetFriendGroupList.Response^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Send: friendlist.GetTroopMemberListReq^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Recv: FriendList.GetTroopMemberList.Response^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Send: friendlist.GetTroopMemberListReq^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Recv: FriendList.GetTroopMemberList.Response^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Successfully loaded group list: 1 in total.^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Syncing friend message history...^[[0m
^[[92m2021-01-26 23:37:01 I/Net 2167655605: Awaiting ConfigPushSvc.PushReq.^[[0m
^[[0m2021-01-26 23:37:01 V/Net 2167655605: Send: MessageSvc.PbGetMsg^[[0m
^[[0m2021-01-26 23:37:02 V/Net 2167655605: Send: MessageSvc.PbDeleteMsg^[[0m
^[[0m2021-01-26 23:37:02 V/Net 2167655605: Send: MessageSvc.PbGetMsg^[[0m
^[[0m2021-01-26 23:37:02 V/Net 2167655605: Send: MessageSvc.PbDeleteMsg^[[0m
^[[0m2021-01-26 23:37:02 V/Net 2167655605: Send: MessageSvc.PbGetMsg^[[0m
^[[0m2021-01-26 23:37:02 V/Net 2167655605: Send: MessageSvc.PbDeleteMsg^[[0m
^[[0m2021-01-26 23:37:02 V/Net 2167655605: Send: MessageSvc.PbGetMsg^[[0m
^[[0m2021-01-26 23:37:02 V/Net 2167655605: Send: MessageSvc.PbDeleteMsg^[[0m
^[[92m2021-01-26 23:37:02 I/Net 2167655605: Syncing friend message history: Success.^[[0m
^[[96m2021-01-26 23:37:03 D/Net 2167655605: Received unknown commandName: ConfigPushSvc.PushDomain^[[0m
^[[0m2021-01-26 23:37:03 V/Net 2167655605: Recv: ConfigPushSvc.PushReq.PushReqResponse.Success^[[0m
^[[0m2021-01-26 23:37:03 V/Net 2167655605: Send: ConfigPushSvc.PushResp^[[0m
^[[92m2021-01-26 23:37:03 I/Net 2167655605: ConfigPushSvc.PushReq: Success.^[[0m
^[[0m2021-01-26 23:37:03 V/Net 2167655605: Recv: ConfigPushSvc.PushReq.PushReqResponse.Success^[[0m
^[[0m2021-01-26 23:37:03 V/Net 2167655605: Send: ConfigPushSvc.PushResp^[[0m
^[[0m2021-01-26 23:41:30 V/Net 2167655605: Send: Heartbeat.Alive^[[0m
^[[0m2021-01-26 23:41:30 V/Net 2167655605: Recv: Heartbeat.Alive.Response^[[0m
```

这是近期log，我只是想知道是我的问题还是插件的问题。

**Comment by PluginsKers** [comment]
我尝试过Talend API（README中的请求方案）
得到的返回也是一样的。
我更换过服务器，我放行了全部端口。
返回不曾改变？到底是我的问题还是插件的问题？

**Comment by PluginsKers** [comment]
我的JDK环境是1.14的：
```
[root@MyCloudServer logs]# java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment 20.3 (build 14.0.2+12)
OpenJDK 64-Bit Server VM 20.3 (build 14.0.2+12, mixed mode, sharing)
```

我使用的是mcl-1.0.4
mirai-api-http-v1.9.6

**Comment by PluginsKers** [comment]
看到了mirai-api-http-v1.9.7的发布
经尝试出现错误：

```java
2021-01-26 23:54:22 I/main: Starting mirai-console...
2021-01-26 23:54:22 I/main: Backend: version 2.0.0, built on 2021-01-15 18:20:03.
2021-01-26 23:54:22 I/main: Frontend Terminal: version 2.0.0, provided by Mamoe Technologies
2021-01-26 23:54:22 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
2021-01-26 23:54:22 I/plugin: Cannot load plugin net.mamoe.mirai-api-http
2021-01-26 23:54:22 E/main: Failed to init MiraiConsole.
java.lang.IllegalStateException: Plugin 'net.mamoe.mirai-api-http' is already loaded and cannot be reloaded.
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:104)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:154)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
```
随后服务端终止。

**Comment by ryoii** [comment]
确保参数格式正确，既然能返回400，表明连接没有问题，插件也正常运行

启动报错请确认mcl的插件目录是否放置了两个mah插件

**Comment by LoS-Light** [comment]
> 看到了mirai-api-http-v1.9.7的发布
> 经尝试出现错误：
> 
> ```java
> 2021-01-26 23:54:22 I/main: Starting mirai-console...
> 2021-01-26 23:54:22 I/main: Backend: version 2.0.0, built on 2021-01-15 18:20:03.
> 2021-01-26 23:54:22 I/main: Frontend Terminal: version 2.0.0, provided by Mamoe Technologies
> 2021-01-26 23:54:22 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
> 2021-01-26 23:54:22 I/plugin: Cannot load plugin net.mamoe.mirai-api-http
> 2021-01-26 23:54:22 E/main: Failed to init MiraiConsole.
> java.lang.IllegalStateException: Plugin 'net.mamoe.mirai-api-http' is already loaded and cannot be reloaded.
>         at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:104)
>         at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
>         at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
>         at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)
>         at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
>         at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:154)
>         at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
>         at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
>         at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
>         at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
>         at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
>         at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
>         at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
>         at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
>         at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
>         at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
>         at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
>         at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
>         at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
>         at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
>         at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
>         at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
>         at org.mozilla.javascript.Context.call(Context.java:554)
>         at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
>         at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
>         at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
>         at com.sun.proxy.$Proxy4.run(Unknown Source)
>         at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
>         at org.itxtech.mcl.Loader.start(Loader.java:128)
>         at org.itxtech.mcl.Loader.main(Loader.java:53)
> ```
> 
> 随后服务端终止。

它有写报错原因
java.lang.IllegalStateException: Plugin 'net.mamoe.mirai-api-http' is already loaded and cannot be reloaded.
'net.mamoe.mirai-api-http' 已经载入了故不能再重新载入
