### ISSUE TITLE
发送本地图片时错误

### ISSUE THREAD

**Issue by liaosunny123** [project-mirai/mirai-api-http#252]
使用了相对路径，用path发送图片，出现如下错误，错误码为0

2021-01-29 15:57:11 E/net.mamoe.mirai-api-http: java.util.concurrent.CancellationException: StandaloneCoroutine was cancelled
java.util.concurrent.CancellationException: StandaloneCoroutine was cancelled
        at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:78)
        at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt)
        at kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1484)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1524)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:807)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:763)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:679)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:645)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1492)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1524)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:807)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:763)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:679)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:645)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1492)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1524)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:807)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:763)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:679)
        at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:640)
        at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:625)
        at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:563)
        at kotlinx.coroutines.JobKt.cancel(Unknown Source)
        at kotlinx.coroutines.JobKt__JobKt.cancel$default(Job.kt:562)
        at kotlinx.coroutines.JobKt.cancel$default(Unknown Source)
        at io.ktor.server.cio.backend.ServerPipelineKt$startServerConnectionPipeline$1.invokeSuspend(ServerPipeline.kt:170)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-01-29 15:57:11 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
2021-01-29 15:57:11 W/stderr: SLF4J: Defaulting to no-operation MDCAdapter implementation.
2021-01-29 15:57:11 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.

**Comment by ryoii** [comment]
应该没有了
