### ISSUE TITLE
[Bug Report] mirai 2.3.1 无法正确发送 Voice 消息

### ISSUE THREAD

**Issue by YunYouJun** [project-mirai/mirai-api-http#268]
- mirai: `2.3.1`
- mirai-api-http: `1.9.7`

API POST 信息 500 错误

```js
    config: {
      url: '/sendGroupMessage',
      method: 'post',
      data: '{"sessionKey":"E79IowvA","target":120117362,"messageChain":[{"type":"Voice","voiceId":null,"url":null,"path":"adnd.amr"}]}',
      headers: [Object],
      baseURL: 'http://127.0.0.1:4859',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
```

mirai-console 报错信息：

NoSuchMethodError uploadAsVoice

```txt
2021-02-03 17:40:31 E/net.mamoe.mirai-api-http: java.lang.NoSuchMethodError: 'java.lang.Object net.mamoe.mirai.utils.ExternalResource$Companion.uploadAsVoice(net.mamoe.mirai.utils.ExternalResource, net.mamoe.mirai.contact.Group, kotlin.coroutines.Continuation)'
java.lang.NoSuchMethodError: 'java.lang.Object net.mamoe.mirai.utils.ExternalResource$Companion.uploadAsVoice(net.mamoe.mirai.utils.ExternalResource, net.mamoe.mirai.contact.Group, kotlin.coroutines.Continuation)'
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:241)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:179)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:310)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Vivapercuore** [comment]
佐证此错误存在

**Comment by ryoii** [comment]
每次发布都有写适配的版本号，如果跨版本使用出现问题，一律认为版本依赖导致。
若要正常使用，请使用正常适配的版本，或避开可能产生冲突的方法，或者等待更新

**Comment by Vivapercuore** [comment]
> 每次发布都有写适应的版本号，如果跨版本使用出现问题，一律认为版本依赖导致。
> 若要正常使用，请使用正常适应的版本，或避免开可能产生冲突的方法，或者等待更新

版本由mcl自动更新选择,建议是否可以和mcl协商读取相关依赖字段?

**Comment by ryoii** [comment]
mcl有关闭自动更新的功能
