### ISSUE TITLE
启动时报错 java.lang.NoClassDefFoundError: io/ktor/server/cio/CIO

### ISSUE THREAD

**Issue by DGCK81LNN** [project-mirai/mirai-api-http#269]
求解

控制台输出：
```
 10:33:53 [INFO] iTXTech Mirai Console Loader version 1.0.4-b4213ea
 10:33:53 [INFO] https://github.com/iTXTech/mirai-console-loader
 10:33:53 [INFO] This program is licensed under GNU AGPL v3
 10:33:53 [DEBUG] Loading script: announcement.js
 10:33:53 [DEBUG] Loading script: boot.js
 10:33:53 [DEBUG] Loading script: config.js
 10:33:53 [DEBUG] Loading script: repo.js
 10:33:53 [DEBUG] Loading script: updater.js
 10:33:54 [INFO] Fetching Mirai Console Loader Announcement...
 10:33:55 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

 10:33:55 [INFO] Verifying "net.mamoe:mirai-console" version 2.3.2
 10:33:55 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.3.2
 10:33:56 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.3.2
 10:33:56 [INFO] Verifying "net.mamoe:mirai-api-http" version 1.9.8
2021-02-04 10:33:58 I/main: Starting mirai-console...
2021-02-04 10:33:58 I/main: Backend: version 2.3.2, built on 2021-02-03 20:36:42
.
2021-02-04 10:33:58 I/main: Frontend Terminal: version 2.3.2, provided by Mamoe
Technologies
2021-02-04 10:33:58 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-htt
p
2021-02-04 10:33:59 I/main: Prepared built-in commands: autoLogin, help, login,
permission, status, stop
2021-02-04 10:33:59 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 12
7.0.0.1:19198
2021-02-04 10:33:59 I/Mirai HTTP API: Http api server is running with authKey: *******
2021-02-04 10:33:59 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2021-02-04 10:34:00 E/Mirai HTTP API: java.lang.NoClassDefFoundError: io/ktor/se
rver/cio/CIO
java.lang.NoClassDefFoundError: io/ktor/server/cio/CIO
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2.invokeSuspend(Mir
aiHttpAPIServer.kt:88)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:665)
Caused by: java.lang.ClassNotFoundException: io.ktor.server.cio.CIO
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClas
s$mirai_console(JvmPluginClassLoader.kt:110)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClas
s(JvmPluginClassLoader.kt:51)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 7 more

2021-02-04 10:34:00 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2021-02-04 10:34:00 I/main: 1 plugin(s) enabled.
2021-02-04 10:34:00 I/main: mirai-console started successfully.
```

纯萌新，不会Java

**Comment by Karlatemp** [comment]
MCL 下载炸了，请从本项目的 Release 界面下载 @PeratX

**Comment by DGCK81LNN** [comment]
解决了？
