### ISSUE TITLE
400参数格式错误

### ISSUE THREAD

**Issue by PluginsKers** [project-mirai/mirai-api-http#275]
请求头部：

Type: POST
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
Content-Type: application/json
Accept: */*
Origin: chrome-extension://aejoelaoggembcahagimdiliamlcdmfm
Accept-Encoding: gzip, deflate
Accept-Language: en,zh-CN;q=0.9,zh;q=0.8

![p](https://img.52craft.cc/images/2021/02/08/2b34fda0abbfaa91c0f68a1612d92b04.png)

复现：

系统：**Linux Centos8.0**

```
[root@VM-8-17-centos bot]# ls
config  data  device.json  libs  logs  MxLibData  plugins  start.sh
```

```
[root@VM-8-17-centos bot]# ./start.sh

2021-02-09 00:46:38 I/main: Starting mirai-console...
2021-02-09 00:46:38 I/main: Backend: version 2.2.0, built on 2021-01-29 12:31:35.
2021-02-09 00:46:38 I/main: Frontend Terminal: version 2.2.0, provided by Mamoe Technologies
2021-02-09 00:46:38 I/net.mamoe.mirai-login-solver-selenium: Loading mirai-login-solver-selenium v1.0-dev-12
2021-02-09 00:46:39 W/net.mamoe.mirai-login-solver-selenium: mirai-login-solver-selenium is not supported.
java.lang.RuntimeException: Exception in loading selenium
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:32)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt:17)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolver.getInstance(SeleniumLoginSolver.kt)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverPluginMode.onLoad(SeleniumLoginSolverPluginMode.kt:32)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:196)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:108)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:154)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
Caused by: java.lang.UnsupportedOperationException: Unsupported Platform: Linux
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:266)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.java:138)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt:63)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.getSetup(SeleniumLoginSolverImpl.kt)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:31)
        ... 16 more
Caused by: java.io.IOException: Cannot run program "xdg-settings": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.commandProcessResult(MxSelenium.java:124)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.commandProcessResult(MxSelenium.java:114)
        at io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:252)
        ... 22 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 26 more

2021-02-09 00:46:39 W/net.mamoe.mirai-login-solver-selenium: Using HttpProxyServer mode
2021-02-09 00:46:39 I/plugin: Successfully loaded plugin net.mamoe.mirai-login-solver-selenium
2021-02-09 00:46:39 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
2021-02-09 00:46:39 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-02-09 00:46:39 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2021-02-09 00:46:39 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:8080
2021-02-09 00:46:39 I/Mirai HTTP API: Http api server is running with authKey: INITKEYB1tqa2tk
2021-02-09 00:46:39 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2021-02-09 00:46:39 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2021-02-09 00:46:39 I/main: 2 plugin(s) enabled.
2021-02-09 00:46:39 I/main: Auto-login xxxxxxxx
2021-02-09 00:46:40 I/Bot.xxxxxxxx: Logging in...
2021-02-09 00:46:41 I/Bot.xxxxxxxx: No OtherClient online.
2021-02-09 00:46:42 I/Bot.xxxxxxxx: Login successful
2021-02-09 00:46:42 I/main: mirai-console started successfully.
2021-02-09 00:46:44 I/Bot.xxxxxxxx: Server requires reconnect.
2021-02-09 00:46:44 I/Bot.xxxxxxxx: Server list: 113.96.12.217:443, 114.221.151.172:443, 14.22.3.51:8080, 42.81.170.122:80, 114.221.148.179:14000, 120.232.19.191:443, 157.148.36.215:80, msfwifi.3g.qq.com:8080.
2021-02-09 00:46:44 I/Bot.xxxxxxxx: Connection lost, retrying login (RequireReconnect(bot=Bot(xxxxxxxx)))
2021-02-09 00:46:44 I/Bot.xxxxxxxx: Logging in...
2021-02-09 00:46:44 I/Bot.xxxxxxxx: No OtherClient online.
2021-02-09 00:46:44 I/Bot.xxxxxxxx: Login successful
2021-02-09 00:46:44 I/Bot.xxxxxxxx: Reconnected successfully in 0.277s
```

`2021-02-09 00:46:39 I/Mirai HTTP API: Http api server is running with authKey: INITKEYB1tqa2tk`
这里核实。

已登录

请求8080有返回。

希望可以修复。

**Comment by ryoii** [comment]
装了滑动验证插件？

**Comment by PluginsKers** [comment]
> 装了滑动验证插件？

requests和滑动验证也有关系吗

**Comment by ryoii** [comment]
因为报错是这个插件导致的，实际可能触发了登录的滑动认证，账号并没有的登录成功，中途产生其他报错
