### ISSUE TITLE
尝试撤回管理员或群主消息时没有正确的返回

### ISSUE THREAD

**Issue by smyhw** [project-mirai/mirai-api-http#289]
* mirai-api-http版本1.9.8  
* mirai-core版本2.4.2  
* mcl版本2.5  
***
机器人是管理员身份，尝试撤回管理员或群主的消息时  
预期应该是返回code10权限不足，  
然鹅，  
接口直接500，并返回错误  
`
Failed to recall message #[74311]: Failed(result=1001, errorMessage=No message meets the requirements)
`
***
console中:  
`
2021-03-24 15:14:53 E/net.mamoe.mirai-api-http: java.lang.IllegalStateException: Failed to recall message #[74312]: Failed(result=1001, errorMessage=No message meets the requirements)
java.lang.IllegalStateException: Failed to recall message #[74312]: Failed(result=1001, errorMessage=No message meets the requirements)
        at net.mamoe.mirai.internal.MiraiImpl.recallMessage$suspendImpl(MiraiImpl.kt:529)
        at net.mamoe.mirai.internal.MiraiImpl$recallMessage$1.invokeSuspend(MiraiImpl.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
`
***
如果多次重复调用，则可能返回
`
[mirai:source:[74312],[1556290415]] had already been recalled.
`
***
同时console中:
`
2021-03-24 15:14:57 E/net.mamoe.mirai-api-http: java.lang.IllegalStateException: [mirai:source:[74312],[1556290415]] had already been recalled.
java.lang.IllegalStateException: [mirai:source:[74312],[1556290415]] had already been recalled.
        at net.mamoe.mirai.internal.MiraiImpl.recallMessage$suspendImpl(MiraiImpl.kt:427)
        at net.mamoe.mirai.internal.MiraiImpl.recallMessage(MiraiImpl.kt)
        at net.mamoe.mirai.message.data.MessageSource$Key.recall(MessageSource.kt:184)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$5$1.invokeSuspend(BaseRoute.kt:297)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$5$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
`
***
然鹅消息并没有/也不可能被成功撤回...

~~似乎可能大概差不多是mirai核心的问题?~~

**Comment by ryoii** [comment]
应该是没有捕获这个异常，导致直接抛出了

**Comment by HoshinoTented** [comment]
你干啥？
