### ISSUE TITLE
启动MCL，走自动更新，直接报错

### ISSUE THREAD

**Issue by STDSuperman** [project-mirai/mirai-api-http#321]
```shell
 10:31:23 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" version 1.64
 10:31:23 [INFO] Verifying "net.mamoe:mirai-console" version 2.6.1
 10:31:23 [INFO] "net.mamoe:mirai-console:2.6.1" is corrupted. Start downloading...
 Downloading mirai-console-2.6.1.jar [==============================] 3.33 MB
 Downloading mirai-console-2.6.1.sha1 [==============================] 40 B
 10:37:06 [WARNING] The local file "net.mamoe:mirai-console" is still corrupted, please check the network.
 10:37:06 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.6.1
 10:37:06 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.6.1
 10:37:07 [INFO] Verifying "net.mamoe:mirai-api-http" version 1.10.0
 10:37:07 [INFO] Verifying "net.mamoe:mirai-login-solver-selenium" version 1.0-dev-16
 10:37:08 [WARNING] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Current version is 2.6.1
Exception in thread "main" java.lang.NoClassDefFoundError: net/mamoe/mirai/console/MiraiConsoleImplementation
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:514)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:422)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:416)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:415)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3325)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3466)
        at java.base/java.lang.Class.getMethod0(Class.java:3452)
        at java.base/java.lang.Class.getMethod(Class.java:2199)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:75)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:129)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.console.MiraiConsoleImplementation
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

跪求解决方案QAQ！！！

**Comment by Him188** [comment]
@PeratX

**Comment by PeratX** [comment]
已经提示了文件损坏，下载后依然损坏

**Comment by STDSuperman** [comment]
> 已经提示了文件损坏，下载后依然损坏

所以我这边重新下载么

**Comment by STDSuperman** [comment]
有结论了么QAQ

**Comment by STDSuperman** [comment]
补充一下，环境是: Win10

**Comment by Him188** [comment]
重新下载

**Comment by STDSuperman** [comment]
好的，感谢啦我试试
