### ISSUE TITLE
想问如何更新到2.0-RC版本

### ISSUE THREAD

**Issue by STDSuperman** [project-mirai/mirai-api-http#349]
手动下载jar包到plugins文件，通过mcl启动时会直接报错。

**Comment by Him188** [comment]
报了什么错

**Comment by STDSuperman** [comment]
> 报了什么错

```shell
2021-05-19 23:53:36 E/main: Failed to init MiraiConsole.
java.lang.IllegalStateException: Plugin 'net.mamoe.mirai-api-http' is already loaded and cannot be reloaded.
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:104)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:157)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:276)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:129)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
```

**Comment by STDSuperman** [comment]
看起来像是与原有的jar包冲突了

**Comment by STDSuperman** [comment]
这里是我删除原有jar包也是无法成功的，我这边是需要进行其他配置吗

**Comment by ryoii** [comment]
删除旧 `jar` 包，在 2.0 分支下参考新的配置文件 [README](https://github.com/project-mirai/mirai-api-http/tree/dev-2.0)

**Comment by STDSuperman** [comment]
> 删除旧 `jar` 包，在 2.0 分支下参考新的配置文件 [README](https://github.com/project-mirai/mirai-api-http/tree/dev-2.0)

```shell

 14:09:59 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" version 1.64
 14:09:59 [INFO] Verifying "net.mamoe:mirai-console" version 2.6.4
 14:09:59 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.6.4
 14:09:59 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.6.4
 14:09:59 [INFO] Verifying "net.mamoe:mirai-api-http" version 1.10.0
 14:09:59 [INFO] "net.mamoe:mirai-api-http:1.10.0" is corrupted. Start downloading...
 Downloading mirai-api-http-1.10.0.jar [==============================] 4.98 MB
 Downloading mirai-api-http-1.10.0.sha1 [==============================] 40 B
 Downloading mirai-api-http-1.10.0.metadata [==============================] 532 B
 14:10:04 [WARNING] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Current version is 2.6.4
2021-05-23 14:10:05 I/main: Starting mirai-console...
2021-05-23 14:10:05 I/main: Backend: version 2.6.4, built on 2021-05-05 23:44:19.
2021-05-23 14:10:05 I/main: Frontend Terminal: version 2.6.4, provided by Mamoe Technologies
2021-05-23 14:10:05 I/main: Welcome to visit https://mirai.mamoe.net/
2021-05-23 14:10:05 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
2021-05-23 14:10:06 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-05-23 14:10:06 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key        
2021-05-23 14:10:06 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:8080    
2021-05-23 14:10:06 I/Mirai HTTP API: Http api server is running with authKey: INITKEYISWjJRIr
2021-05-23 14:10:06 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2021-05-23 14:10:06 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2021-05-23 14:10:06 I/main: 1 plugin(s) enabled.
2021-05-23 14:10:06 I/main: mirai-console started successfully.
```

手动下载2.0启动MCL会自动下载1.10.0版本并使用

**Comment by STDSuperman** [comment]
求解是不是仍需要修改项目其他配置或者是需要做其他操作，官方这边似乎还未给出详细文档，目前采用手动下载并放置到plugins文件夹下，然后启动mcl是无效的

**Comment by ryoii** [comment]
关闭mcl的自动更新

**Comment by STDSuperman** [comment]
> 关闭mcl的自动更新

好的我试试，感谢
