### ISSUE TITLE
v2.0-RC2 http release 接口报错

### ISSUE THREAD

**Issue by Kaiyokun** [project-mirai/mirai-api-http#358]
### 问题
在使用**http adapter**时，在`verify`->`bind`->除了（`verify`, `bind`, `release`）之外任意接口->`release`这样的流程下，`release`接口会失败，*mirai console*显示如下；但是若直接`verify`->`bind`->`release`则一切正常。
```
2021-05-29 23:17:55 E/net.mamoe.mirai-api-http: java.lang.ClassCastException: class net.mamoe.mirai.api.http.adapter.http.session.HttpAuthedSession cannot be cast to class net.mamoe.mirai.api.http.context.session.AuthedSession (net.mamoe.mirai.api.http.adapter.http.session.HttpAuthedSession and net.mamoe.mirai.api.http.context.session.AuthedSession are in unnamed module of loader net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader @7158daf2)
java.lang.ClassCastException: class net.mamoe.mirai.api.http.adapter.http.session.HttpAuthedSession cannot be cast to class net.mamoe.mirai.api.http.context.session.AuthedSession (net.mamoe.mirai.api.http.adapter.http.session.HttpAuthedSession and net.mamoe.mirai.api.http.context.session.AuthedSession are in unnamed module of loader net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader @7158daf2)
        at net.mamoe.mirai.api.http.adapter.http.router.VerifyKt$authRouter$1$$special$$inlined$httpBind$2$1.invokeSuspend(dsl.kt:244)
        at net.mamoe.mirai.api.http.adapter.http.router.VerifyKt$authRouter$1$$special$$inlined$httpBind$2$1.invoke(dsl.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at net.mamoe.mirai.api.http.adapter.http.auth.Authorization$install$1.invokeSuspend(Authorization.kt:32)
        at net.mamoe.mirai.api.http.adapter.http.auth.Authorization$install$1.invoke(Authorization.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### 环境
- net.mamoe:mirai-console version 2.6.4
- net.mamoe:mirai-console-terminal version 2.6.4
- net.mamoe:mirai-core-all version 2.6.4

### 配置
```yaml
adapters:
  - http
  - ws
enableVerify: true
verifyKey: huaweisucks
debug: false
singleMode: false
cacheSize: 4096
adapterSettings:
  http:
    host: localhost
    port: 8080
    cors: [*]
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1
```

**Comment by yuejieyao** [comment]
我遇到了同样的问题,由于上一个sessionkey释放失败会导致websocket接收相同的message,接收的数量=没释放的sessionkey数量,目前只能重启mcl来解决
