### ISSUE TITLE
java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'

### ISSUE THREAD

**Issue by artxia** [project-mirai/mirai-api-http#373]
```
21:58:42 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" version 1.64

 21:58:42 [INFO] Verifying "net.mamoe:mirai-console" version 2.7-M1

 21:58:42 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.7-M1

 21:58:43 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.7-M1

2021-06-20 21:58:43 I/main: Starting mirai-console...

2021-06-20 21:58:43 I/main: Backend: version 2.7-M1, built on 2021-06-20 02:21:33.

2021-06-20 21:58:43 I/main: Frontend Terminal: version 2.7-M1, provided by Mamoe Technologies

2021-06-20 21:58:43 I/main: Welcome to visit https://mirai.mamoe.net/

2021-06-20 21:58:43 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http

2021-06-20 21:58:44 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop

2021-06-20 21:58:44 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 127.0.0.1:8080

2021-06-20 21:58:44 I/Mirai HTTP API: Http api server is running with authKey: z******E

2021-06-20 21:58:44 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false

2021-06-20 21:58:44 I/net.mamoe.mirai-api-http: 上报模块启用状态: true

2021-06-20 21:58:44 I/main: 1 plugin(s) enabled.

2021-06-20 21:58:44 I/main: Auto-login 2****0

2021-06-20 21:58:44 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'

java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'

	at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt:48)

	at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt)

	at io.ktor.features.CORS$Feature.install(CORS.kt:517)

	at io.ktor.features.CORS$Feature.install(CORS.kt:509)

	at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:68)

	at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:45)

	at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)

	at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:29)

	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)

	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:138)

	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:270)

	at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:53)

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)

	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by fatinghenji** [comment]
相同问题，请求修复

**Comment by nutshell0xd7** [comment]
相同问题，下午重启后便无法使用

**Comment by ryoii** [comment]
mirai core 升级到了 kotlin 1.5, 即 core 和 mah 版本目前不兼容

**Comment by Him188** [comment]
MAH 使用了无保证的实验性 Duration API 导致不兼容

**Comment by ryoii** [comment]
看了一下，你这个应该还是1.x版本的吧

**Comment by Trinkle23897** [comment]
把根目录config.json里面的2.7-M1替换成2.6.7，beta替换成stable就可以了
