### ISSUE TITLE
E/Mirai HTTP API: java.lang.NoSuchMethodError...

### ISSUE THREAD

**Issue by I0gan** [project-mirai/mirai-api-http#384]
突然发现http api不能用了，请问下这是mirai-api-http的问题么？

```

2021-06-25 12:49:16 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt:48)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt)
        at io.ktor.features.CORS$Feature.install(CORS.kt:517)
        at io.ktor.features.CORS$Feature.install(CORS.kt:509)
        at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:68)
        at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:45)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:29)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:138)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:270)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by ryoii** [comment]
版本不对，如果用了 core 2.7, 到 release 页面手动下载 1.12.0 版本

或升级至 2.x, 或将 core 回退至 2.6

**Comment by 22528850** [comment]
插件的sha1对不上会自动更新最新版本的mirai-api-http，但是自动下载的最新版本是1.10.0的。

**Comment by 22528850** [comment]
> 版本不对，如果用了 core 2.7, 到 release 页面手动下载 1.12.0 版本
> 
> 或升级至 2.x, 或将 core 回退至 2.6

插件的sha1对不上会自动更新最新版本的mirai-api-http，但是自动下载的最新版本是1.10.0的。

**Comment by 22528850** [comment]
> 版本不对，如果用了 core 2.7, 到 release 页面手动下载 1.12.0 版本
> 
> 或升级至 2.x, 或将 core 回退至 2.6

mcl判断插件sha1值和插件文件不一致会自动更新插件，但是自动更新的mirai-api-http版本是1.10.0的

**Comment by 22528850** [comment]
mcl的config文件mirai-console的包版本改回2.5.0版本就好了。mcl自动更新mc到2.7版本导致的

**Comment by 22528850** [comment]
阿里云仓库那边没找到最新的1.12.0版本的mirai-api-http

**Comment by I0gan** [comment]
解决了，谢谢！

**Comment by ryoii** [comment]
releae 页面获取最新版本
