### ISSUE TITLE
java.lang.IllegalArgumentException: data must len % 8 == 0 && len >= 16 but given -1

### ISSUE THREAD

**Issue by nekolr** [project-mirai/mirai-api-http#390]
运行了一段时间是正常的，然后突然就不行了，报错如下：

```
2021-07-05 16:04:12 V/Bot.2957675529: Event: GroupMessagePreSendEvent(target=Group(482994311), message=标题：#7 進撃LOG 10作者：木の子[mirai:image:{13A2843E-1B7C-9018-CDF7-168C99AC2B16}.jpg][mirai:image:{1953145D-4461-7B81-7C89-9F765609A40D}.jpg][mirai:image:{649C9BD0-2F2D-AE62-2541-6B19D0C4FF92}.jpg][mirai:image:{BC9335C7-07C1-1208-3592-A737B0058E91}.jpg][mirai:image:{2A4A4674-2EBA-A48C-B34E-4FA1A429A2BC}.jpg][mirai:image:{6B684F32-FF54-EA5C-247D-905FE65341DD}.jpg][mirai:image:{5C1FFC4B-3EE3-4FDC-008B-3418C222574A}.jpg][mirai:image:{5F17E621-2351-7E74-11E9-A385E648B449}.jpg][mirai:image:{34518AC7-2220-C2BD-187D-8FD9ACE8BC87}.jpg][mirai:image:{7F6F8953-032A-3DE5-7A9B-ED7E505D7DE9}.jpg][mirai:image:{33AFF382-ABD1-5BAE-FF3D-8CAA557684CC}.jpg][mirai:image:{9EE86512-AFDE-5644-EA2E-D5B3031675EA}.jpg][mirai:image:{A8E32115-B5C8-19E2-BFB2-BC15893D0133}.jpg][mirai:image:{2A9D952C-0087-2DC4-820A-AA532C7CC6D5}.jpg][mirai:image:{8A1844E0-454D-CC52-01F4-3A4A1C443089}.jpg][mirai:image:{7E8DAD8F-0370-5970-6226-8E0BC9E12CBD}.jpg][mirai:image:{8491A0F6-CC89-2155-A9D4-42A330D8F269}.jpg][mirai:image:{07BA9819-F39A-F98A-8CF7-A39D9CEB0A63}.jpg][mirai:image:{C7004D8C-998A-05F7-547F-A763C093FBE8}.jpg][mirai:image:{D6853F0F-B5D0-E9A1-79EA-73DDA3900E74}.jpg][mirai:image:{1320C7FF-CEE8-9E42-8054-CCED19589C08}.jpg][mirai:image:{51E2ACDA-4B15-59D1-C0D6-F9B2102E6CEF}.jpg][mirai:image:{3914D12C-14D1-5D66-9D34-61F559E16E39}.jpg][mirai:image:{4BC7B7D7-ACFD-28C0-6FE1-6E1747ABC86C}.jpg][mirai:image:{AD893EDD-6E18-55CB-DD26-9AB41B624FE9}.jpg][mirai:image:{491EA02A-D71B-ED73-3BDD-3B04DAA4328B}.jpg][mirai:image:{F5554E97-D398-5405-5F7D-F3BB801048DE}.jpg][mirai:image:{561948E7-7382-A375-0BB5-CA083C5EECF5}.jpg][mirai:image:{5B82208C-220D-2905-17BE-0EA83BDE6220}.jpg][mirai:image:{FF5B2F7E-C488-4243-7FD0-4591AB5FD841}.jpg][mirai:image:{51451A57-77CF-D962-3CEF-5F4E29159739}.jpg][mirai:image:{13D7F106-C2B5-98F5-8E1B-657DD87ED4D0}.jpg][mirai:image:{88CF9841-8EA8-2B8F-0A9D-79BDC2BE7B16}.jpg][mirai:image:{C4DF7B65-7431-A314-594B-192A739C48B1}.jpg][mirai:image:{51F6CEF5-9648-52EB-AD5F-39F0BF8BD7E2}.jpg][mirai:image:{C5861C8E-5124-8B48-C1E2-4AF516F0DDFE}.jpg][mirai:image:{1771A5C1-86CF-D366-5766-236CDCD8368D}.jpg]发布时间：2021-07-04 06:26:35)
2021-07-05 16:04:13 V/Bot.2957675529: Group(482994311) <- 标题：#7 進撃LOG 10作者：木の子[mirai:image:{13A2843E-1B7C-9018-CDF7-168C99AC2B16}.jpg][mirai:image:{1953145D-4461-7B81-7C89-9F765609A40D}.jpg][mirai:image:{649C9BD0-2F2D-AE62-2541-6B19D0C4FF92}.jpg][mirai:image:{BC9335C7-07C1-1208-3592-A737B0058E91}.jpg][mirai:image:{2A4A4674-2EBA-A48C-B34E-4FA1A429A2BC}.jpg][mirai:image:{6B684F32-FF54-EA5C-247D-905FE65341DD}.jpg][mirai:image:{5C1FFC4B-3EE3-4FDC-008B-3418C222574A}.jpg][mirai:image:{5F17E621-2351-7E74-11E9-A385E648B449}.jpg][mirai:image:{34518AC7-2220-C2BD-187D-8FD9ACE8BC87}.jpg][mirai:image:{7F6F8953-032A-3DE5-7A9B-ED7E505D7DE9}.jpg][mirai:image:{33AFF382-ABD1-5BAE-FF3D-8CAA557684CC}.jpg][mirai:image:{9EE86512-AFDE-5644-EA2E-D5B3031675EA}.jpg][mirai:image:{A8E32115-B5C8-19E2-BFB2-BC15893D0133}.jpg][mirai:image:{2A9D952C-0087-2DC4-820A-AA532C7CC6D5}.jpg][mirai:image:{8A1844E0-454D-CC52-01F4-3A4A1C443089}.jpg][mirai:image:{7E8DAD8F-0370-5970-6226-8E0BC9E12CBD}.jpg][mirai:image:{8491A0F6-CC89-2155-A9D4-42A330D8F269}.jpg][mirai:image:{07BA9819-F39A-F98A-8CF7-A39D9CEB0A63}.jpg][mirai:image:{C7004D8C-998A-05F7-547F-A763C093FBE8}.jpg][mirai:image:{D6853F0F-B5D0-E9A1-79EA-73DDA3900E74}.jpg][mirai:image:{1320C7FF-CEE8-9E42-8054-CCED19589C08}.jpg][mirai:image:{51E2ACDA-4B15-59D1-C0D6-F9B2102E6CEF}.jpg][mirai:image:{3914D12C-14D1-5D66-9D34-61F559E16E39}.jpg][mirai:image:{4BC7B7D7-ACFD-28C0-6FE1-6E1747ABC86C}.jpg][mirai:image:{AD893EDD-6E18-55CB-DD26-9AB41B624FE9}.jpg][mirai:image:{491EA02A-D71B-ED73-3BDD-3B04DAA4328B}.jpg][mirai:image:{F5554E97-D398-5405-5F7D-F3BB801048DE}.jpg][mirai:image:{561948E7-7382-A375-0BB5-CA083C5EECF5}.jpg][mirai:image:{5B82208C-220D-2905-17BE-0EA83BDE6220}.jpg][mirai:image:{FF5B2F7E-C488-4243-7FD0-4591AB5FD841}.jpg][mirai:image:{51451A57-77CF-D962-3CEF-5F4E29159739}.jpg][mirai:image:{13D7F106-C2B5-98F5-8E1B-657DD87ED4D0}.jpg][mirai:image:{88CF9841-8EA8-2B8F-0A9D-79BDC2BE7B16}.jpg][mirai:image:{C4DF7B65-7431-A314-594B-192A739C48B1}.jpg][mirai:image:{51F6CEF5-9648-52EB-AD5F-39F0BF8BD7E2}.jpg][mirai:image:{C5861C8E-5124-8B48-C1E2-4AF516F0DDFE}.jpg][mirai:image:{1771A5C1-86CF-D366-5766-236CDCD8368D}.jpg]发布时间：2021-07-04 06:26:35
2021-07-05 16:04:13 V/Bot.2957675529: Event: GroupMessagePostSendEvent(target=Group(482994311), message=标题：#7 進撃LOG 10作者：木の子[mirai:image:{13A2843E-1B7C-9018-CDF7-168C99AC2B16}.jpg][mirai:image:{1953145D-4461-7B81-7C89-9F765609A40D}.jpg][mirai:image:{649C9BD0-2F2D-AE62-2541-6B19D0C4FF92}.jpg][mirai:image:{BC9335C7-07C1-1208-3592-A737B0058E91}.jpg][mirai:image:{2A4A4674-2EBA-A48C-B34E-4FA1A429A2BC}.jpg][mirai:image:{6B684F32-FF54-EA5C-247D-905FE65341DD}.jpg][mirai:image:{5C1FFC4B-3EE3-4FDC-008B-3418C222574A}.jpg][mirai:image:{5F17E621-2351-7E74-11E9-A385E648B449}.jpg][mirai:image:{34518AC7-2220-C2BD-187D-8FD9ACE8BC87}.jpg][mirai:image:{7F6F8953-032A-3DE5-7A9B-ED7E505D7DE9}.jpg][mirai:image:{33AFF382-ABD1-5BAE-FF3D-8CAA557684CC}.jpg][mirai:image:{9EE86512-AFDE-5644-EA2E-D5B3031675EA}.jpg][mirai:image:{A8E32115-B5C8-19E2-BFB2-BC15893D0133}.jpg][mirai:image:{2A9D952C-0087-2DC4-820A-AA532C7CC6D5}.jpg][mirai:image:{8A1844E0-454D-CC52-01F4-3A4A1C443089}.jpg][mirai:image:{7E8DAD8F-0370-5970-6226-8E0BC9E12CBD}.jpg][mirai:image:{8491A0F6-CC89-2155-A9D4-42A330D8F269}.jpg][mirai:image:{07BA9819-F39A-F98A-8CF7-A39D9CEB0A63}.jpg][mirai:image:{C7004D8C-998A-05F7-547F-A763C093FBE8}.jpg][mirai:image:{D6853F0F-B5D0-E9A1-79EA-73DDA3900E74}.jpg][mirai:image:{1320C7FF-CEE8-9E42-8054-CCED19589C08}.jpg][mirai:image:{51E2ACDA-4B15-59D1-C0D6-F9B2102E6CEF}.jpg][mirai:image:{3914D12C-14D1-5D66-9D34-61F559E16E39}.jpg][mirai:image:{4BC7B7D7-ACFD-28C0-6FE1-6E1747ABC86C}.jpg][mirai:image:{AD893EDD-6E18-55CB-DD26-9AB41B624FE9}.jpg][mirai:image:{491EA02A-D71B-ED73-3BDD-3B04DAA4328B}.jpg][mirai:image:{F5554E97-D398-5405-5F7D-F3BB801048DE}.jpg][mirai:image:{561948E7-7382-A375-0BB5-CA083C5EECF5}.jpg][mirai:image:{5B82208C-220D-2905-17BE-0EA83BDE6220}.jpg][mirai:image:{FF5B2F7E-C488-4243-7FD0-4591AB5FD841}.jpg][mirai:image:{51451A57-77CF-D962-3CEF-5F4E29159739}.jpg][mirai:image:{13D7F106-C2B5-98F5-8E1B-657DD87ED4D0}.jpg][mirai:image:{88CF9841-8EA8-2B8F-0A9D-79BDC2BE7B16}.jpg][mirai:image:{C4DF7B65-7431-A314-594B-192A739C48B1}.jpg][mirai:image:{51F6CEF5-9648-52EB-AD5F-39F0BF8BD7E2}.jpg][mirai:image:{C5861C8E-5124-8B48-C1E2-4AF516F0DDFE}.jpg][mirai:image:{1771A5C1-86CF-D366-5766-236CDCD8368D}.jpg]发布时间：2021-07-04 06:26:35, exception=null, receipt=net.mamoe.mirai.message.MessageReceipt@6e24d69c)
2021-07-05 16:53:14 V/Bot.2957675529: Event: MemberHonorChangeEvent.Achieve(member=NormalMember(2957675529), honorType=TALKATIVE)
2021-07-05 22:26:28 W/stderr: Jul 05, 2021 10:26:28 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
2021-07-05 22:26:28 W/stderr: WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
2021-07-05 22:26:28 W/stderr: java.lang.IllegalArgumentException: data must len % 8 == 0 && len >= 16 but given -1
2021-07-05 22:26:28 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:223)
2021-07-05 22:26:28 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:291)
2021-07-05 22:26:28 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:315)
2021-07-05 22:26:28 W/stderr:   at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:218)
2021-07-05 22:26:28 W/stderr:   at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:104)
2021-07-05 22:26:28 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:86)
2021-07-05 22:26:28 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:79)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2021-07-05 22:26:28 W/stderr:   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
2021-07-05 22:26:28 W/stderr:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
2021-07-05 22:26:28 W/stderr:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2021-07-05 22:26:28 W/stderr:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-07-05 22:26:28 W/stderr:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-07-05 22:26:28 W/stderr:   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-07-05 22:26:28 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
2021-07-05 22:26:28 W/stderr:
2021-07-05 22:26:28 W/stderr:
2021-07-05 22:26:33 W/stderr: Jul 05, 2021 10:26:33 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
2021-07-05 22:26:33 W/stderr: WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
2021-07-05 22:26:33 W/stderr: java.lang.IllegalArgumentException: data must len % 8 == 0 && len >= 16 but given -1
2021-07-05 22:26:33 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:223)
2021-07-05 22:26:33 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:291)
2021-07-05 22:26:33 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:315)
2021-07-05 22:26:33 W/stderr:   at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:218)
2021-07-05 22:26:33 W/stderr:   at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:104)
2021-07-05 22:26:33 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:86)
2021-07-05 22:26:33 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:79)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2021-07-05 22:26:33 W/stderr:   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
2021-07-05 22:26:33 W/stderr:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
2021-07-05 22:26:33 W/stderr:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2021-07-05 22:26:33 W/stderr:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-07-05 22:26:33 W/stderr:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-07-05 22:26:33 W/stderr:   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-07-05 22:26:33 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
2021-07-05 22:26:33 W/stderr:
2021-07-05 22:26:33 W/stderr:
2021-07-06 22:21:38 W/stderr: Jul 06, 2021 10:21:38 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
2021-07-06 22:21:38 W/stderr: WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
2021-07-06 22:21:38 W/stderr: java.lang.IllegalArgumentException: data must len % 8 == 0 && len >= 16 but given -1
2021-07-06 22:21:38 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:223)
2021-07-06 22:21:38 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:291)
2021-07-06 22:21:38 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:315)
2021-07-06 22:21:38 W/stderr:   at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:218)
2021-07-06 22:21:38 W/stderr:   at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:104)
2021-07-06 22:21:38 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:86)
2021-07-06 22:21:38 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:79)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2021-07-06 22:21:38 W/stderr:   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
2021-07-06 22:21:38 W/stderr:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
2021-07-06 22:21:38 W/stderr:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2021-07-06 22:21:38 W/stderr:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-07-06 22:21:38 W/stderr:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-07-06 22:21:38 W/stderr:   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-07-06 22:21:38 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
2021-07-06 22:21:38 W/stderr:
2021-07-06 22:21:38 W/stderr:
2021-07-06 22:21:43 W/stderr: Jul 06, 2021 10:21:43 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
2021-07-06 22:21:43 W/stderr: WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
2021-07-06 22:21:43 W/stderr: java.lang.IllegalArgumentException: data must len % 8 == 0 && len >= 16 but given -1
2021-07-06 22:21:43 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:223)
2021-07-06 22:21:43 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:291)
2021-07-06 22:21:43 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:315)
2021-07-06 22:21:43 W/stderr:   at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:218)
2021-07-06 22:21:43 W/stderr:   at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:104)
2021-07-06 22:21:43 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:86)
2021-07-06 22:21:43 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:79)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2021-07-06 22:21:43 W/stderr:   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
2021-07-06 22:21:43 W/stderr:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
2021-07-06 22:21:43 W/stderr:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2021-07-06 22:21:43 W/stderr:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-07-06 22:21:43 W/stderr:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-07-06 22:21:43 W/stderr:   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-07-06 22:21:43 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)
2021-07-06 22:21:43 W/stderr:
2021-07-06 22:21:43 W/stderr:
```

**Comment by ryoii** [comment]
@Him188

**Comment by ryoii** [comment]
core 已有相关issue
