### ISSUE TITLE
mah插件启动报错

### ISSUE THREAD

**Issue by Minepig** [project-mirai/mirai-api-http#396]
mah插件在启动的时候似乎启动失败了，报错信息如下
```
2021-07-13 19:26:43 E/Mirai HTTP API: io.ktor.application.DuplicateApplicationFeatureException: Conflicting application feature is already installed with the same key as `Default Headers`
io.ktor.application.DuplicateApplicationFeatureException: Conflicting application feature is already installed with the same key as `Default Headers`
        at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:82)
        at io.ktor.application.ApplicationFeatureKt.install$default(ApplicationFeature.kt:60)
        at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:43)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:306)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:31)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:323)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:295)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:136)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:268)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$2.invokeSuspend(CIOApplicationEngine.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

mirai版本：2.6.7
mah版本：1.12.0

**Comment by ryoii** [comment]
提供一下配置文件

**Comment by Minepig** [comment]
> 提供一下配置文件
```
cors: 
  - '*'
host: 127.0.0.1
port: 9000
authKey: ###
cacheSize: 4096
enableWebsocket: true
report: 
  enable: false
  groupMessage: 
    report: true
  friendMessage: 
    report: true
  tempMessage: 
    report: true
  eventMessage: 
    report: true
  destinations: []
  extraHeaders: {}

heartbeat: 
  enable: false
  delay: 1000
  period: 15000
  destinations: []
  extraBody: {}

  extraHeaders: {}
```

**Comment by ryoii** [comment]
可能有不兼容的修改，使用 1.12.0 的插件，尽量使用 2.7-M1 的 core
