### ISSUE TITLE
插件启动报错日志

### ISSUE THREAD

**Issue by gxlffly** [project-mirai/mirai-api-http#405]
插件启动报错,日志如下
2021-07-18 00:05:14 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt:48)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt)
        at io.ktor.features.CORS$Feature.install(CORS.kt:517)
        at io.ktor.features.CORS$Feature.install(CORS.kt:509)
        at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:68)
        at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:45)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:29)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:138)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:270)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

配置如下:
cors: 
  - '*'
host: 0.0.0.0
port: 8080
authKey: INITKEY0yS6UFkV
cacheSize: 4096
enableWebsocket: false
report: 
  enable: false
  groupMessage: 
    report: true
  friendMessage: 
    report: true
  tempMessage: 
    report: true
  eventMessage: 
    report: true
  destinations: []
  extraHeaders: {}

heartbeat: 
  enable: false
  delay: 1000
  period: 15000
  destinations: []
  extraBody: {}

  extraHeaders: {}

系统:centos8

重现步骤
1 安装mcl-installer-72b890d-linux-amd64,一路全默认
`./mcl`
退出console后
再安装API插件
`./mcl --update-package net.mamoe:mirai-api-http --type plugin --channel stable
`
再运行
`./mcl`

**Comment by gxlffly** [comment]
已经找到问题了.
API的版本和mirai的版本不一至.不能使用自动安装API.要手动安装

**Comment by gxlffly** [comment]
> 插件启动报错日志，如下
> 2021-07-18 00:05:14 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
> java .lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
> at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt: 48)
> 在 net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt)
> 在 io.ktor.features.CORS$Feature.install(CORS.kt:517)
> 在 io.ktor。 features.CORS$Feature.install(CORS.kt:509)
> at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:68)
> at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt :68)千吨：45）
> 在 net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)
> 在 net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt: 29)
> 在 io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)
> 在 io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:138)
> 在 io.vironengineApplicationEnloadserver. .start(ApplicationEngineEnvironmentReloading.kt:270)
> 在 io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:53)
> 在 kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt ) )
> 在 kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 在 kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 在 kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.execute5Task(CoroutineScheduler) )
> 在 kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 在 kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> 
> 配置如下：
> cors：
> 
> * '*'
>   主机：0.0.0.0
>   端口：8080 
>   authKey：INITKEY0yS6UFkV 
>   cacheSize：4096 
>   enableWebsocket：false 
>   report：
>   enable：false 
>   groupMessage：
>   report：
>   truefriendMessage：
>   report：true 
>   tempMessage：
>   report：true 
>   eventMessage：
>   report：true 
>   destination：[] 
>   extraHeaders ：{}
> 
> 心跳：
> 启用：假
> 延迟：1000
> 周期：15000
> 目的地：[]
> extraBody：{}
> 
> 额外标头：{}
> 
> 系统：centos8
> 
> 重现步骤
> 1安装MCL-安装-72b890d-Linux的AMD64，全一路默认
> `./mcl`
> 退出控制台后
> 再安装API插件
> `./mcl --update-package net.mamoe:mirai-api-http --type plugin --channel stable `
> 再运行
> `./mcl`
