### ISSUE TITLE
文件上传接口请求后报错，返回值无错误信息

### ISSUE THREAD

**Issue by Fripine** [project-mirai/mirai-api-http#426]
接口：
[POST] /file/upload

mirai控制台报错：
2021-07-28 14:31:50 E/net.mamoe.mirai-api-http: java.lang.NullPointerException
java.lang.NullPointerException
        at net.mamoe.mirai.api.http.adapter.internal.action.FileKt.onUploadFile(file.kt:41)
        at net.mamoe.mirai.api.http.adapter.internal.action.FileKt$onUploadFile$1.invokeSuspend(file.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-07-28 14:34:49 E/ExternalResourceLeakObserver: A resource leak occurred, use ExternalResource.close to avoid it!! (holder=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile$ResourceHolder@1665c20). Add jvm option `-Dmirai.resource.creation.stack.enabled=true` to show creation stack track

请求得到的返回值：
{"code":500,"msg":""}

刷新群文件列表后，发现文件已成功上传

**Comment by Fripine** [comment]
mirai-core 2.7-M2
mirai-api-http-v2.1.0

**Comment by SinoAHpx** [comment]
附议

**Comment by ryoii** [comment]
Fixed
