### ISSUE TITLE
 该填的东西都填对了，8080端口也没有被占用，防火墙也关掉了，就是死活连接不了mcl

### ISSUE THREAD

**Issue by yuzhiboyou456** [project-mirai/mirai-api-http#435]
PS C:\Users\Lenovo\Music> python bot.py
[2021-08-08 18:34:51,133][INFO]: initializing app...
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\python\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Program Files\python\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\python\lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    app.launch_blocking()
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\graia\application\__init__.py", line 1574, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\graia\application\__init__.py", line 1464, in initialize
    await self.authenticate()
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\graia\application\utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\graia\application\__init__.py", line 301, in authenticate
    async with self.session.post(
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [远程计算机拒绝网络连 接。]

**Comment by yuzhiboyou456** [comment]
mcl-1.0.3,mirai-api-http-1.10.0

**Comment by ryoii** [comment]
提供mcl有无报错日志，提供mah的配置文件

**Comment by SinCerely023** [comment]
同mcl mah版本同报错，我是通过指定mirai-console版本解决的，希望能提供一点参考：

我这边mcl启动日志有一行warning
`[WARN] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Current version is 2.7-M2`
并在最后出现了Java的报错信息。我是通过
`mcl --update-package net.mamoe:mirai-console --channel stable --version 2.5.0`
命令指定mirai-console版本为2.5.0之后解决的，mcl日志无warning无error。

个人认为是mcl没有更新2.0版本mah但是mirai-console更新导致的问题，恰好Graia没有完成mah2.0的适配。另外提醒一下最新版本的Graia有bug，适当回退版本。
