### ISSUE TITLE
使用/SendGroupMessage发送语音导致资源泄露

### ISSUE THREAD

**Issue by Numendacil** [project-mirai/mirai-api-http#458]
mirai-api-http version: 2.2.0
mirai-console version: 2.7.0

报错信息：

2021-09-04 12:37:24 E/null: A resource leak occurred, use ExternalResource.close to avoid it!! (holder=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile$ResourceHolder@78893eb1)
net.mamoe.mirai.internal.utils.ExternalResourceLeakObserver$ExternalResourceCreateStackTrace
        at java.base/java.lang.Thread.getStackTrace(Thread.java:1596)
        at net.mamoe.mirai.internal.utils.ExternalResourceHolder.<init>(ExternalImageImpls.kt:71)
        at net.mamoe.mirai.internal.utils.ExternalResourceImplByFile$ResourceHolder.<init>(ExternalImageImpls.kt:105)
        at net.mamoe.mirai.internal.utils.ExternalResourceImplByFile.<init>(ExternalImageImpls.kt:112)
        at net.mamoe.mirai.utils.ExternalResource$Companion.create(ExternalResource.kt:163)
        at net.mamoe.mirai.utils.ExternalResource$Companion.create$default(ExternalResource.kt:159)
        at net.mamoe.mirai.utils.ExternalResource$Companion.create(ExternalResource.kt:145)
        at net.mamoe.mirai.utils.FileCacheStrategy$TempCache.newCache(FileCacheStrategy.kt:107)
        at net.mamoe.mirai.utils.ExternalResource$Companion.create(ExternalResource.kt:189)
        at net.mamoe.mirai.utils.ExternalResource$Companion.create$default(ExternalResource.kt:188)
        at net.mamoe.mirai.api.http.adapter.internal.convertor.ConvertorKt$voiceLikeToMessage$2.invokeSuspend(convertor.kt:127)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

使用了cyanray/mirai-cpp，发送的请求为
{
    "type": "Voice",
    "voiceId": null,
    "url": "https://pb.nichi.co/near-heavy-during",
    "path": null,
    "base64": null
}

**Comment by Numendacil** [comment]
看了下代码，好像是因为 #377 导致的

**Comment by Numendacil** [comment]
好像是因为 #377 导致的，但不知道为什么只有发送语音会报错而图片不会

**Comment by ryoii** [comment]
不是一个问题

**Comment by Numendacil** [comment]
确实，我把那个cpp封装用websocket重写了一遍还是出现了Resource leak，所以目前有什么解决的办法吗，还是说不管就好了

**Comment by ryoii** [comment]
应该是某个上传语音的接口没有关闭

**Comment by ryoii** [comment]
排查了下下只是core没有识别到资源被关闭，实际上对应的流已经被关闭了，应该没有问题
