### ISSUE TITLE
为什么复制教程的yml运行后报错

### ISSUE THREAD

**Issue by SundayZhao** [project-mirai/mirai-api-http#463]
将这一段

adapterSettings:
  http:
    host: localhost
    port: 8080
    cors: [*]
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1

改为adapterSettings:{}可以成功运行

2021-09-08 00:20:19 E/net.mamoe.mirai-api-http: java.lang.NoSuchFieldError: Default
java.lang.NoSuchFieldError: Default
        at net.mamoe.mirai.api.http.adapter.http.HttpAdapter$setting$2.invoke(HttpAdapter.kt:38)
        at net.mamoe.mirai.api.http.adapter.http.HttpAdapter$setting$2.invoke(HttpAdapter.kt:12)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.api.http.adapter.http.HttpAdapter.getSetting$mirai_api_http(HttpAdapter.kt)
        at net.mamoe.mirai.api.http.adapter.http.HttpAdapter.initKtorAdapter(HttpAdapter.kt:20)
        at net.mamoe.mirai.api.http.adapter.MahKtorAdapter.initAdapter(MahKtorAdapter.kt:62)
        at net.mamoe.mirai.api.http.MahPluginImpl.start(MahPluginImpl.kt:45)
        at net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:48)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:206)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:277)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:151)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)

**Comment by ryoii** [comment]
提供插件的版本号，core的版本号

随便提供一下配置文件的放置目录，最好是全路径

**Comment by SundayZhao** [comment]
> 提供插件的版本号，核心的版本号
> 
> 随便提供一下配置文件的目录，最好是全路径

mirai-core-all  2.7.0
mirai-api-http  v2.1.0.mirai
目录:E:\mcl-1.2.2\config\net.mamoe.mirai-api-http

**Comment by ryoii** [comment]
是不是缩减不对

**Comment by SundayZhao** [comment]
> 是不是缩进不对

我尝试使用Tab缩进也依然报错
![image](https://user-images.githubusercontent.com/26807747/133011404-daf587d7-300b-4b81-97e1-b401ace5e4e3.png)

**Comment by ryoii** [comment]
2.1可能不支持 2.7.0 的 core, 试一试 2.3.0 的插件

**Comment by SundayZhao** [comment]
> 2.1可能不支持 2.7.0 的 core, 试一试 2.3.0 的插件

十分感谢，我将引用的net.mamoe:mirai-console包从2.5.0改为2.7.0-all问题解决
