### ISSUE TITLE
mcl 仓库中的 mirai-api-http 版本过低

### ISSUE THREAD

**Issue by Nutr1t07** [project-mirai/mirai-api-http#484]
通过MCL指令安装的插件版本为 1.10.0，将导致依赖问题。使用手动安装方式安装最新版本 2.3.1 能够解决。虽然是无伤大雅的小问题，但是 README 的描述似乎存在误导性？如果 `mcl` 不能及时更新至新版的话还是不要推荐使用它安装插件吧。
<details>
<summary>日志</summary>
<pre>
$ ./mcl --update-package net.mamoe:mirai-api-http --channel stable --type plugin
  20:55:52 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  20:55:52 [INFO] https://github.com/iTXTech/mirai-console-loader
  20:55:52 [INFO] This program is licensed under GNU AGPL v3
  20:55:52 [INFO] Package "net.mamoe:mirai-api-http" has been added.
</pre>

<pre>
$ ./mcl                                                                         
  20:55:56 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  20:55:56 [INFO] https://github.com/iTXTech/mirai-console-loader
  20:55:56 [INFO] This program is licensed under GNU AGPL v3
  20:55:56 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  20:55:57 [INFO] Verifying "net.mamoe:mirai-console" v2.8.0-M1
  20:55:57 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.8.0-M1
  20:55:58 [INFO] Verifying "net.mamoe:mirai-core-all" v2.8.0-M1
  20:55:58 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  20:55:58 [INFO] Verifying "net.mamoe:mirai-api-http" v
  20:55:58 [ERROR] "net.mamoe:mirai-api-http" is corrupted.
 Downloading mirai-api-http-1.10.0.jar [==============================] 4.98 MB                         
 Downloading mirai-api-http-1.10.0.sha1 [==============================] 40 B                  
 Downloading mirai-api-http-1.10.0.metadata [==============================] 532 B                   
  20:56:04 [INFO] Fetching Mirai Console Loader Announcement...
  20:56:04 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

  20:56:04 [WARN] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Current version is 2.8.0-M1
2021-10-02 20:56:04 I/main: Starting mirai-console...
2021-10-02 20:56:05 I/main: Backend: version 2.8.0-M1, built on 2021-09-22 17:49:01.
2021-10-02 20:56:05 I/main: Frontend Terminal: version 2.8.0-M1, provided by Mamoe Technologies
2021-10-02 20:56:05 I/main: Welcome to visit https://mirai.mamoe.net/
2021-10-02 20:56:05 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2021-10-02 20:56:05 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v1.10.0
2021-10-02 20:56:05 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-10-02 20:56:05 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2021-10-02 20:56:05 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2021-10-02 20:56:05 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:8080
2021-10-02 20:56:05 I/Mirai HTTP API: Http api server is running with authKey: INITKEY6zESqIkU
2021-10-02 20:56:05 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2021-10-02 20:56:05 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2021-10-02 20:56:05 I/main: 2 plugin(s) enabled.
2021-10-02 20:56:05 I/main: mirai-console started successfully.
2021-10-02 20:56:05 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt:48)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt)
        at io.ktor.features.CORS$Feature.install(CORS.kt:517)
        at io.ktor.features.CORS$Feature.install(CORS.kt:509)
        at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:68)
        at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:45)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:29)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:138)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:270)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
</pre>
</details>

**Comment by ryoii** [comment]
#381

**Comment by Nutr1t07** [comment]
> 虽然是无伤大雅的小问题，但是 README 的描述似乎存在误导性？如果 `mcl` 不能及时更新至新版的话还是不要推荐使用它安装插件吧。

尽管1.x升级会引发版本兼容问题，但是我的问题在于，假如使用最新版的mirai安装会引发依赖问题，为什么要在readme里推荐mcl呢？
