### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property botAsMember has not been initialized 获取群数据异常

### ISSUE THREAD

**Issue by vikieow** [project-mirai/mirai-api-http#522]
```
2021-12-22 17:21:17 E/net.mamoe.mirai-api-http: kotlin.UninitializedPropertyAccessException: lateinit property botAsMember has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property botAsMember has not been initialized
        at net.mamoe.mirai.internal.contact.GroupImpl.getBotAsMember(GroupImpl.kt:80)
        at net.mamoe.mirai.contact.Group.getBotPermission(Group.kt:78)
        at net.mamoe.mirai.api.http.adapter.internal.dto.GroupDTO.<init>(contact.kt:58)
        at net.mamoe.mirai.api.http.adapter.internal.action.InfomationKt.onGetGroupList(infomation.kt:31)
        at net.mamoe.mirai.api.http.adapter.http.router.InfoKt$infoRouter$1$$special$$inlined$respondDTOStrategy$2.invokeSuspend(dsl.kt:216)
        at net.mamoe.mirai.api.http.adapter.http.router.InfoKt$infoRouter$1$$special$$inlined$respondDTOStrategy$2.invoke(dsl.kt)
        at net.mamoe.mirai.api.http.adapter.http.router.InfoKt$infoRouter$1$$special$$inlined$httpAuthedGet$2$1.invokeSuspend(dsl.kt:221)
        at net.mamoe.mirai.api.http.adapter.http.router.InfoKt$infoRouter$1$$special$$inlined$httpAuthedGet$2$1.invoke(dsl.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at net.mamoe.mirai.api.http.adapter.http.auth.Authorization$install$1.invokeSuspend(Authorization.kt:41)
        at net.mamoe.mirai.api.http.adapter.http.auth.Authorization$install$1.invoke(Authorization.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
        at io.ktor.server.cio.CIOApplicationEngine$handleRequest$2.invokeSuspend(CIOApplicationEngine.kt:192)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by ryoii** [comment]
提供下 插件版本号， core版本号

**Comment by vikieow** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vikieow** [comment]
> 提供下 插件版本号， core版本号

{
  "js_optimization_level": -1,
  "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
  "maven_repo": [
    "https://maven.aliyun.com/repository/public"
  ],
  "packages": [
    {
      "id": "net.mamoe:mirai-console",
      "channel": "beta",
      "version": "2.9.0-RC2",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
      "channel": "beta",
      "version": "2.9.0-RC2",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-core-all",
      "channel": "beta",
      "version": "2.9.0-RC2",
      "type": "libs",
      "versionLocked": false
    },
    {
      "id": "org.itxtech:mcl-addon",
      "channel": "c122",
      "version": "1.2.2",
      "type": "plugins",
      "versionLocked": false
    },
    {
      "id": "net.mamoe:mirai-api-http",
      "channel": "stable-v2",
      "version": "2.4.0",
      "type": "plugins",
      "versionLocked": false
    }
  ],
  "disabled_scripts": [],
  "proxy": "",
  "log_level": 1,
  "script_props": {}
}



版本配置如下，这个问题在我之前的配置中也频繁出现

**Comment by Him188** [comment]
mirai 2.10 在遇到这个情况时会输出一个日志, 内容大致为 "在 GroupImpl 时遇到了意料之中的问题 ......", 如有遇到请提交到 mamoe/mirai 的 issues 以帮助解决问题

**Comment by vikieow** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vikieow** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
