### ISSUE TITLE
HeartbeatFailedException 重连之后一段时间被Killed

### ISSUE THREAD

**Issue by BATTERIA** [project-mirai/mirai-api-http#531]
发生异常HeartbeatFailedException 重连之后一段时间被Killed
是1月9日晚上十点多服务有什么波动吗

```
HeartbeatFailedException: StatHeartbeat, recoverable=true, cause=PacketTimeoutException(message=Timeout receiving Heartbeat response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)
HeartbeatFailedException: StatHeartbeat, recoverable=true, cause=PacketTimeoutException(message=Timeout receiving Heartbeat response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateOK$heartbeatJobs$1$1.invoke(NettyNetworkHandler.kt:361)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateOK$heartbeatJobs$1$1.invoke(NettyNetworkHandler.kt:361)
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:251)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateOK$heartbeatJobs$1.invoke(NettyNetworkHandler.kt:407)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateOK$heartbeatJobs$1.invoke(NettyNetworkHandler.kt:360)
        at net.mamoe.mirai.internal.network.components.TimeBasedHeartbeatSchedulerImpl$launchHeartbeatJobAsync$1.invokeSuspend(HeartbeatScheduler.kt:108)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: PacketTimeoutException(message=Timeout receiving Heartbeat response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)
        ... 13 more
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

^[[0m2022-01-09 22:33:16 V/: Loading server list from cache.^[[0m
^[[92m2022-01-09 22:33:16 I/: Server list: 120.232.130.99:443, msfwifi.3g.qq.com:8080, 157.148.36.89:80, 183.47.99.24:8080, 42.81.184.82:80, 180.163.212.180:14000, 220.196.132.240:443, 101.91.40.83:443.^[[0m
^[[92m2022-01-09 22:33:16 I/: ECDH key is invalid, start to fetch ecdh public key from server.^[[0m
^[[92m2022-01-09 22:33:55 I/: Successfully fetched ecdh public key from server.^[[0m
^[[0m2022-01-09 22:34:02 V/: Send: wtlogin.exchange_emp^[[0m
^[[0m2022-01-09 22:34:05 V/: Recv: wtlogin.exchange_emp^[[0m
^[[0m2022-01-09 22:34:06 V/: Send: StatSvc.register(online)^[[0m
^[[0m2022-01-09 22:34:06 V/: Recv: StatSvc.register^[[0m
^[[0m2022-01-09 22:34:12 V/: Recv: ConfigPushSvc.PushReq^[[0m
^[[92m2022-01-09 22:34:14 I/: Server list: 101.91.40.21:443, msfwifi.3g.qq.com:8080, 114.222.112.229:14000, 120.232.19.197:443, 221.238.41.89:80, 157.255.13.124:80, 153.3.50.239:443, 183.47.98.105:8080.^[[0m
^[[0m2022-01-09 22:34:14 V/: Saving bdh session to cache^[[0m
^[[0m2022-01-09 22:34:15 V/: Saving server list to cache^[[0m
^[[92m2022-01-09 22:34:15 I/: Scheduled key refresh in 23h 55min 0.0s.^[[0m
^[[0m2022-01-09 22:34:15 V/: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)^[[0m
^[[92m2022-01-09 22:34:15 I/: Scheduled refresh login session in 19d 23h 55min 0.0s.^[[0m
^[[0m2022-01-09 22:34:15 V/: Recv: ConfigPushSvc.PushReq^[[0m
^[[0m2022-01-09 22:34:17 V/: Saving bdh session to cache^[[0m
^[[0m2022-01-09 22:34:17 V/: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)^[[0m
^[[0m2022-01-09 22:38:55 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)^[[0m

**Comment by ryoii** [comment]
看起来只是网络状态不稳定

**Comment by ryoii** [comment]
长时间没有反馈，暂时关闭issue
