### ISSUE TITLE
按照教程启动MCL时报错

### ISSUE THREAD

**Issue by StirrerCymbal5zn** [project-mirai/mirai-api-http#545]
这是完整日志
root@iugiu72023:~# ./mcl
 13:54:41 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
 13:54:41 [INFO] https://github.com/iTXTech/mirai-console-loader
 13:54:41 [INFO] This program is licensed under GNU AGPL v3
 13:54:41 [INFO] MCL Addon is installed! Website: https://github.com/iTXTech/mcl-addon
 13:54:41 [WARN] To remove MCL Addon, run "./mcl --disable-script addon" and "./mcl --remove-package org.itxtech:mcl-addon --delete"
 13:54:42 [INFO] Verifying "net.mamoe:mirai-console" v
 13:54:42 [ERROR] "net.mamoe:mirai-console" is corrupted.
 Downloading mirai-console-2.10.0.jar [==============================] 3.40 MB                         
 Downloading mirai-console-2.10.0.sha1 [==============================] 40 B                  
 13:56:23 [ERROR] The local file "net.mamoe:mirai-console" is still corrupted, please check the network.
 13:56:23 [INFO] Verifying "net.mamoe:mirai-console-terminal" v
 13:56:23 [ERROR] "net.mamoe:mirai-console-terminal" is corrupted.
 Downloading mirai-console-terminal-2.10.0.jar [==============================] 1.24 MB                         
 Downloading mirai-console-terminal-2.10.0.sha1 [==============================] 40 B                  
 13:56:40 [INFO] Verifying "net.mamoe:mirai-core-all" v
 13:56:40 [ERROR] "net.mamoe:mirai-core-all" is corrupted.
 Downloading mirai-core-all-2.10.0.jar [==============================] 35.26 MB                        
 Downloading mirai-core-all-2.10.0.sha1 [==============================] 40 B                  
 14:00:29 [ERROR] The local file "net.mamoe:mirai-core-all" is still corrupted, please check the network.
 14:00:29 [INFO] Verifying "org.itxtech:mcl-addon" v
 14:00:29 [ERROR] "org.itxtech:mcl-addon" is corrupted.
 Downloading mcl-addon-1.2.2.jar [==============================] 19.97 KB                       
 Downloading mcl-addon-1.2.2.sha1 [==============================] 40 B                  
 14:00:41 [INFO] Fetching Mirai Console Loader Announcement...
 14:00:41 [INFO] Mirai Console Loader Announcement:

主要是这一段

 14:00:42 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.util.zip.ZipException: zip END header not found (boot.js#98)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at script(boot.js:98)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy1.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
	at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
	at org.itxtech.mcl.Loader.start(Loader.java:176)
	at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:321)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:287)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	... 20 more

**Comment by StirrerCymbal5zn** [comment]
主要是这一段
 14:00:42 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.util.zip.ZipException: zip END header not found (boot.js#98)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at script(boot.js:98)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy1.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
	at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
	at org.itxtech.mcl.Loader.start(Loader.java:176)
	at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:321)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:287)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	... 20 more
