### ISSUE TITLE
启动时报错double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)

### ISSUE THREAD

**Issue by StirrerCymbal5zn** [project-mirai/mirai-api-http#546]
09:39:37 [WARN] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Current version is 2.10.0
  09:39:37 [WARN] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-RC. Current version is 2.10.0
2022-02-27 09:39:39 I/main: Starting mirai-console...
2022-02-27 09:39:39 I/main: Backend: version 2.10.0, built on 2022-01-31 16:02:35.
2022-02-27 09:39:39 I/main: Frontend Terminal: version 2.10.0, provided by Mamoe Technologies
2022-02-27 09:39:39 I/main: Welcome to visit https://mirai.mamoe.net/
2022-02-27 09:39:40 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2022-02-27 09:39:40 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v1.10.0
2022-02-27 09:39:40 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-02-27 09:39:41 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-02-27 09:39:41 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2022-02-27 09:39:41 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2022-02-27 09:39:41 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:8080
2022-02-27 09:39:41 I/Mirai HTTP API: Http api server is running with authKey: **
2022-02-27 09:39:41 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2022-02-27 09:39:41 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2022-02-27 09:39:41 I/main: 3 plugin(s) enabled.
2022-02-27 09:39:41 I/main: mirai-console started successfully.
2022-02-27 09:39:41 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
	at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt:48)
	at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt)
	at io.ktor.features.CORS$Feature.install(CORS.kt:517)
	at io.ktor.features.CORS$Feature.install(CORS.kt:509)
	at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:68)
	at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:45)
	at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)
	at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:29)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:138)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:270)
	at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:53)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

>

**Comment by Him188** [comment]
net.mamoe.mirai-api-http v1.10.0 版本太低

**Comment by StirrerCymbal5zn** [comment]
> net.mamoe.mirai-api-http v1.10.0 版本太低

抱歉，是否是我没理解清楚文档。mcl不是可以自动更新和启动的吗

**Comment by FightingAction** [comment]
> net.mamoe.mirai-api-http v1.10.0 版本太低

请问该如何更新版本?  谢谢

**Comment by Him188** [comment]
将channel更换为 v2？忘了，看 https://github.com/project-mirai/mirai-api-http

**Comment by landall** [comment]
> 将channel更换为 v2？忘了，看 https://github.com/project-mirai/mirai-api-http#%E4%BD%BF%E7%94%A8-mirai-console-loader-%E5%AE%89%E8%A3%85mirai-api-http

https://docs.mirai.mamoe.net/UserManual.html#%E4%BA%86%E8%A7%A3%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83

这个文档没更新。

**Comment by landall** [comment]
而且stable-v2下载下来的仍然是1.10版本。。。
