### ISSUE TITLE
有时发消息会出错 过一会重启又好了

### ISSUE THREAD

**Issue by 383494** [project-mirai/mirai-api-http#563]
如题 错误信息：
E/MAH Access: java.util.concurrent.CancellationException: java.lang.IllegalStateException: Timeout waiting for ConfigPush.
java.util.concurrent.CancellationException: java.lang.IllegalStateException: Timeout waiting for ConfigPush.
    at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect$suspendImpl(SelectorNetworkHandler.kt:108)
    at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect(SelectorNetworkHandler.kt)
    at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect(NetworkHandler.kt:173)
    at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect$default(NetworkHandler.kt:169)
    at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:138)
    at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.sendMessageImpl(SendMessageHandler.kt:365)
    at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.sendMessage(SendMessageHandler.kt:336)
    at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:189)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.internal.action.MessageKt.sendMessage(message.kt:67)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.internal.action.MessageKt.onSendGroupMessage(message.kt:108)    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$$special$$inlined$respondDTOStrategy$3.invokeSuspend(dsl.kt:205)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$$special$$inlined$respondDTOStrategy$3.invoke(dsl.kt)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$$special$$inlined$httpAuthedPost$2$1.invokeSuspend(dsl.kt:214)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$$special$$inlined$httpAuthedPost$2$1.invoke(dsl.kt)
    at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
    at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
    at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
    at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
    at mirai-api-http-2.4.0.jar//io.ktor.routing.Routing.executeResult(Routing.kt:155)
    at mirai-api-http-2.4.0.jar//io.ktor.routing.Routing.interceptor(Routing.kt:39)
    at mirai-api-http-2.4.0.jar//io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
    at mirai-api-http-2.4.0.jar//io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
    at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
    at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invokeSuspend(Authorization.kt:41)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invoke(Authorization.kt)  
    at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
    at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.intercept(HttpRouterAccessHandler.kt:36)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.access$intercept(HttpRouterAccessHandler.kt:25)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invokeSuspend(HttpRouterAccessHandler.kt:91)
    at mirai-api-http-2.4.0.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invoke(HttpRouterAccessHandler.kt)
    at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
    at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
    at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
    at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
    at mirai-api-http-2.4.0.jar//io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
    at mirai-api-http-2.4.0.jar//io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
    at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
    at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
    at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
    at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
    at mirai-api-http-2.4.0.jar//io.ktor.server.cio.CIOApplicationEngine$handleRequest$2.invokeSuspend(CIOApplicationEngine.kt:192)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalStateException: Timeout waiting for ConfigPush.
    at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl.syncConfigPush(ConfigPushProcessor.kt:36)
    at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl$syncConfigPush$1.invokeSuspend(ConfigPushProcessor.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    ... 4 more

**Comment by ryoii** [comment]
大概是你网络不好，发不出去？这个看起来像是 core 丢出来的异常

**Comment by ryoii** [comment]
长时间未回复，先关闭 issue
