### ISSUE TITLE
无法正常链接

### ISSUE THREAD

**Issue by ABCDCreeper** [project-mirai/mirai-api-http#566]
使用1x版本：2022-05-05 10:18:44.097 | DEBUG    | graia.saya:require:76 - require modules.KeywordDetection
2022-05-05 10:18:44.835 | INFO     | graia.saya:require:95 - module loading finished: modules.KeywordDetection
2022-05-05 10:18:44.836 | DEBUG    | graia.saya:require:76 - require modules.BiliResolve
[2022-05-05 10:18:44,839][INFO]: initializing app...
modules.KeywordDetection::模块加载成功!!!
Traceback (most recent call last):
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 8080)

2x：2022-05-05 10:18:44.097 | DEBUG    | graia.saya:require:76 - require modules.KeywordDetection
2022-05-05 10:18:44.835 | INFO     | graia.saya:require:95 - module loading finished: modules.KeywordDetection
2022-05-05 10:18:44.836 | DEBUG    | graia.saya:require:76 - require modules.BiliResolve
[2022-05-05 10:18:44,839][INFO]: initializing app...
modules.KeywordDetection::模块加载成功!!!
Traceback (most recent call last):
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shutdown/Service/MiraiBot/saya_plugins_collection/main.py", line 42, in <module>
    app.launch_blocking()
  File "/home/shutdown/.local/lib/python3.9/site-packages/graia/application/__init__.py", line 1613, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/shutdown/.local/lib/python3.9/site-packages/graia/application/__init__.py", line 1503, in initialize
    await self.authenticate()
  File "/home/shutdown/.local/lib/python3.9/site-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/shutdown/.local/lib/python3.9/site-packages/graia/application/__init__.py", line 301, in authenticate
    async with self.session.post(
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 0.0.0.0:8080 ssl:default [Connect call failed ('0.0.0.0', 8080)]
shutdown@ShutdownServer:~/Service/MiraiBot/saya_plugins_collection$ python3 main.py 
2022-05-05 10:23:25.910 | DEBUG    | graia.saya:require:76 - require modules.KeywordDetection
2022-05-05 10:23:26.688 | INFO     | graia.saya:require:95 - module loading finished: modules.KeywordDetection
2022-05-05 10:23:26.689 | DEBUG    | graia.saya:require:76 - require modules.BiliResolve
[2022-05-05 10:23:26,690][INFO]: initializing app...
modules.KeywordDetection::模块加载成功!!!
Traceback (most recent call last):
  File "/home/shutdown/Service/MiraiBot/saya_plugins_collection/main.py", line 42, in <module>
    app.launch_blocking()
  File "/home/shutdown/.local/lib/python3.9/site-packages/graia/application/__init__.py", line 1613, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/shutdown/.local/lib/python3.9/site-packages/graia/application/__init__.py", line 1503, in initialize
    await self.authenticate()
  File "/home/shutdown/.local/lib/python3.9/site-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/shutdown/.local/lib/python3.9/site-packages/graia/application/__init__.py", line 304, in authenticate
    response.raise_for_status()
  File "/home/shutdown/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://0.0.0.0:8080/auth')

使用netstat查看，也没有开放8080端口，以上是graia-saya

**Comment by MrXiaoM** [comment]
你的情况很可能是 graia-saya 实现的是 mah 1.x 的接口而你正在使用 mah 2.x
详见[迁移文档](https://github.com/project-mirai/mirai-api-http/blob/master/docs/misc/Migration2.md)

解决方法：将 mah 降级为 1.x ([下载地址](https://github.com/project-mirai/mirai-api-http/releases/tag/v1.12.0))

**Comment by ABCDCreeper** [comment]
> 你的情况很可能是 graia-saya 实现的是 mah 1.x 的接口而你正在使用 mah 2.x 详见[迁移文档](https://github.com/project-mirai/mirai-api-http/blob/master/docs/misc/Migration2.md)
> 
> 解决方法：将 mah 降级为 1.x ([下载地址](https://github.com/project-mirai/mirai-api-http/releases/tag/v1.12.0)) 或者按照迁移文档进行channel更新

我上面标了当使用1x和2x保的错

**Comment by ABCDCreeper** [comment]
1x:ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 8080)
2x:aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://0.0.0.0:8080/auth')

**Comment by ABCDCreeper** [comment]
而且，mah根本没有开放8080端口

**Comment by ryoii** [comment]
提供一下 mcl 的启动日志，特别是 mah 有关的部分，我怀疑启动已经有问题了

**Comment by ryoii** [comment]
长时间未回复，先关闭 issue
