### ISSUE TITLE
发送群消息出错

### ISSUE THREAD

**Issue by CitienTZ** [project-mirai/mirai-api-http#600]
版本：2.5.2
正常使用了一阵子，没有变动过配置，突然就发送群消息报错，请求数据如下：
![image](https://user-images.githubusercontent.com/15061388/183268799-4699a174-d8a5-476a-bf1d-ba2a8ed5b7d8.png)
![image](https://user-images.githubusercontent.com/15061388/183268802-d5517235-8d67-49d4-be96-5f37073d35aa.png)
报错信息如下：
![image](https://user-images.githubusercontent.com/15061388/183268803-45730474-d410-4fde-bcc6-1804655004fe.png)
![image](https://user-images.githubusercontent.com/15061388/183268808-7a056820-f21f-4b84-b1ac-37c04937d317.png)
2022-08-07 07:14:17 E/MAH Access: java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:146)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol.kt:46)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSenderProtocol.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by CitienTZ** [comment]
找到了[https://github.com/mamoe/mirai/issues/2149](url)
