### ISSUE TITLE
mcl运行中报了个错

### ISSUE THREAD

**Issue by landall** [project-mirai/mirai-api-http#615]
mcl最新版，我手动更新的mirai-api-http v2.6.1
mcl官方库里的2.5.2有那个不启动webhook的bug
不知道这个错误是不是跟2.6.1版本有关系。

        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.http.cio.HttpHeadersMap$getAll$4.invoke(HttpHeadersMap.kt:96)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.http.cio.CIOHeaders.getAll(CIOHeaders.kt:30)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.server.engine.BaseApplicationEngineKt.verifyHostHeader(BaseApplicationEngine.kt:91)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.server.engine.BaseApplicationEngineKt.access$verifyHostHeader(BaseApplicationEngine.kt:1)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.server.engine.BaseApplicationEngine$installDefaultInterceptors$3.invokeSuspend(BaseApplicationEngine.kt:83)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.server.engine.BaseApplicationEngine$installDefaultInterceptors$3.invoke(BaseApplicationEngine.kt)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.server.engine.BaseApplicationEngine$installDefaultInterceptors$3.invoke(BaseApplicationEngine.kt)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at mirai-api-http-v2.6.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invokeSuspend(Authorization.kt:41)
        at mirai-api-http-v2.6.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invoke(Authorization.kt)
        at mirai-api-http-v2.6.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invoke(Authorization.kt)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at mirai-api-http-v2.6.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.intercept(HttpRouterAccessHandler.kt:36)
        at mirai-api-http-v2.6.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.access$intercept(HttpRouterAccessHandler.kt:25)
        at mirai-api-http-v2.6.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invokeSuspend(HttpRouterAccessHandler.kt:91)
        at mirai-api-http-v2.6.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invoke(HttpRouterAccessHandler.kt)
        at mirai-api-http-v2.6.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invoke(HttpRouterAccessHandler.kt)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:127)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
        at mirai-api-http-v2.6.1.mirai2.jar[shared]//io.ktor.server.cio.CIOApplicationEngine$handleRequest$2.invokeSuspend(CIOApplicationEngine.kt:196)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by ryoii** [comment]
日志截全一点，感觉没有特别完整

**Comment by landall** [comment]
> 日志截全一点，感觉没有特别完整

我不知道该怎么截取日志……mcl好像需要maven装啥日志插件类，否则就直接输出到屏幕了……但这个已经出了我的知识范围了

**Comment by ryoii** [comment]
日志给全，实在不知道从哪里开始，就从第一行开始

**Comment by landall** [comment]
那下次吧，screen屏幕里暂时只有这么多了。。。

**Comment by cssxsh** [comment]
@landall 

logs 文件夹下面有日志文件
