### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Arturia169** [project-mirai/mirai-api-http#635]
[92m2022-10-15 08:47:40 I/main: Starting mirai-console...[0m[m
[92m2022-10-15 08:47:40 I/main: Backend: version 2.12.1, built on 2022-07-31 09:49:27.[0m[m
[92m2022-10-15 08:47:40 I/main: Frontend Terminal: version 2.12.1, provided by Mamoe Technologies[0m[m
[92m2022-10-15 08:47:40 I/main: Welcome to visit https://mirai.mamoe.net/[0m[m
[91m2022-10-15 08:47:41 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".[0m[m
[91m2022-10-15 08:47:41 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation[0m[m
[91m2022-10-15 08:47:41 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.[0m[m
[92m2022-10-15 08:47:41 I/plugin: Successfully loaded plugin MCL Addon v2.0.2[0m[m
[92m2022-10-15 08:47:42 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop[0m[m
[92m2022-10-15 08:47:42 I/MCL Addon: iTXTech MCL Version: 2.1.0-71ec418[0m[m
[91m2022-10-15 08:47:42 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用[0m[m
[92m2022-10-15 08:47:42 I/main: 1 plugin(s) enabled.[0m[m
[91m2022-10-15 08:47:42 W/WindowHelperJvm: Failed to initialize module `java.desktop`
java.lang.UnsatisfiedLinkError: /root/mlc/java/lib/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
	at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.Toolkit.loadLibraries(Unknown Source)
	at java.desktop/java.awt.Toolkit.initStatic(Unknown Source)
	at java.desktop/java.awt.Toolkit.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.mamoe.mirai.utils.WindowHelperJvm.<clinit>(SwingSolver.kt:148)
	at net.mamoe.mirai.utils.LoginSolver.<clinit>(LoginSolver.jvm.kt:92)
	at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:221)
	at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:625)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:186)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:170)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$10$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:287)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:245)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
	at org.itxtech.mcl.Loader.start(Loader.java:189)
	at org.itxtech.mcl.Loader.main(Loader.java:79)
[0m[m
[92m2022-10-15 08:47:42 I/main: Auto-login 335569218[0m[m
[91m2022-10-15 08:47:42 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...[0m[m
[92m2022-10-15 08:47:43 I/Bot.335569218: Loaded account secrets from local cache.[0m[m
[92m2022-10-15 08:47:43 I/Bot.335569218: Saved account secrets to local cache for fast login.[0m[m
[92m2022-10-15 08:47:44 I/Bot.335569218: Login successful.[0m[m
[0m2022-10-15 08:47:47 V/Bot.335569218: Event: BotOnlineEvent(bot=Bot(335569218))[0m[m
[92m2022-10-15 08:47:47 I/Bot.335569218: Bot login successful.[0m[m
[92m2022-10-15 08:47:47 I/main: mirai-console started successfully.[0m[m

**Comment by ryoii** [comment]
把 mah 插件移除试试，我猜测是MCL的问题

**Comment by Arturia169** [comment]
> 把 mah 插件移除试试，我猜测是MCL的问题

![image](https://user-images.githubusercontent.com/69199123/195979557-b89ac0b8-8f72-40d5-89db-ed7c78863aa6.png)
重装了一遍这次没有mah插件一样的报错
![image](https://user-images.githubusercontent.com/69199123/195979577-409f1d34-ab4c-4aa3-a762-a911b8b5691e.png)

**Comment by ryoii** [comment]
所以说了是 mcl 的问题

你系统缺少依赖的动态库了

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/196095907-0fb06b36-f2d7-455f-87a8-c7dda10aa929.png)
解决了我用的xshell终端 把这个选项点掉就正常了
