### ISSUE TITLE
收到语音消息后控制台报错，且webhook接口没有推送。

### ISSUE THREAD

**Issue by wordweb** [project-mirai/mirai-api-http#643]
控制台提示是如下信息：

2022-11-12 04:54:00 W/stderr: Exception in thread "DefaultDispatcher-worker-16" java.lang.UnsupportedOperationException: Could not fetch URL for audio {11806A36-C22D-9990-AB90-59C09FBE629D}.amr
2022-11-12 04:54:00 W/stderr:   at net.mamoe.mirai.internal.message.data.OnlineAudioImpl.getUrlForDownload(audio.kt:118)
2022-11-12 04:54:00 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.MessageKt.toDTO(message.kt:70)
2022-11-12 04:54:00 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.MessageKt.toDTO(message.kt:52)
2022-11-12 04:54:00 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.MessageKt.toDTO(message.kt:42)
2022-11-12 04:54:00 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.ConvertorKt.toDTO(convertor.kt:43)
2022-11-12 04:54:01 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.http.HttpAdapter.onReceiveBotEvent(HttpAdapter.kt:42)
2022-11-12 04:54:01 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.context.MahContext$handleBotEvent$1$1.invokeSuspend(MahContext.kt:116)
2022-11-12 04:54:01 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-11-12 04:54:01 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-11-12 04:54:01 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-11-12 04:54:01 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
2022-11-12 04:54:01 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-11-12 04:54:01 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-11-12 04:54:01 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4b4bfd5f, Dispatchers.Default]

**Comment by ryoii** [comment]
看来是获取不到语音的下载地址

**Comment by ryoii** [comment]
尝试更新 core 本地 #638
