### ISSUE TITLE
2.6.2配置文件根据模板填写运行报错

### ISSUE THREAD

**Issue by rogue233** [project-mirai/mirai-api-http#652]
配置文件复制了模板文件，仅修改了key，运行报错
![图片](https://user-images.githubusercontent.com/80617099/206392262-1b98351b-467d-4bae-a84b-3d7d62cb101d.png)

**Comment by rogue233** [comment]
配置文件如下：
## 配置文件中的值，全为默认值

## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http
  - ws

## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: true
verifyKey: INITKEYopnF82al

## 开启一些调式信息
debug: false

## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
## 开启后，接口中任何 sessionKey 不需要传递参数
## 若 console 中有多个 bot 登录，则行为未定义
## 确保 console 中只有一个 bot 登陆时启用
singleMode: false

## 历史消息的缓存大小
## 同时，也是 http adapter 的消息队列容量
cacheSize: 4096

## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8080
    cors: ["*"]
    unreadQueueMaxSize: 100
  
  ## 详情看 websocket adapter 使用说明 配置
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1

**Comment by rogue233** [comment]
配置文件如下：
`## 配置文件中的值，全为默认值

## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http
  - ws

## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: true
verifyKey: INITKEYopnF82al

## 开启一些调式信息
debug: false

## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
## 开启后，接口中任何 sessionKey 不需要传递参数
## 若 console 中有多个 bot 登录，则行为未定义
## 确保 console 中只有一个 bot 登陆时启用
singleMode: false

## 历史消息的缓存大小
## 同时，也是 http adapter 的消息队列容量
cacheSize: 4096

## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8080
    cors: ["*"]
    unreadQueueMaxSize: 100
  
  ## 详情看 websocket adapter 使用说明 配置
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1`

**Comment by rogue233** [comment]
配置如下：
adapters:
  - http
  - ws
enableVerify: true
verifyKey: INITKEYopnF82al
debug: false
singleMode: false
cacheSize: 4096
adapterSettings:
  http:
    host: localhost
    port: 8080
    cors: ["*"]
    unreadQueueMaxSize: 100
  
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1

**Comment by ryoii** [comment]
您要不把配置文件直接上传上来吧，这个根本不是你真正运行的配置文件

**Comment by rogue233** [comment]
运行日志如下：
''2022-12-08 16:19:26 I/main: Starting mirai-console...
2022-12-08 16:19:26 I/main: 

==================================[ Mirai consosle 2.13.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2022-12-08 16:19:26 I/main: Backend: version 2.13.0, built on 2022-11-01 10:47:11.
2022-12-08 16:19:26 I/main: Frontend Terminal: version 2.13.0, provided by Mamoe Technologies
2022-12-08 16:19:26 I/main: Welcome to visit https://mirai.mamoe.net/
2022-12-08 16:19:27 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-12-08 16:19:27 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-12-08 16:19:27 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin AutoGroup v2.0.3
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin HitHit v2.0.0
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin 提醒开播机器人 v1.3.2
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.6.2
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin hundun.fleet.reminder v0.1.3
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin groupUnrecall v0.2.0
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin MiraiNative v2.0.0-cssxsh
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin Reporter v1.4.0
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin OneBot v0.3.4
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin PatPat v2.0.1
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin ThrowIt-Mirai v1.2
2022-12-08 16:19:29 I/plugin: Successfully loaded plugin MCL Addon v2.0.2
2022-12-08 16:19:29 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-12-08 16:19:30 I/AutoGroup: 开始折磨群友
2022-12-08 16:19:30 I/HitHit: 缓存已自动清理
2022-12-08 16:19:30 I/HitHit: 锤人插件已加载
2022-12-08 16:19:30 I/stdout: [2022-12-08 16:19:30] [DEBUG] cn.hutool.log.LogFactory: Use [Hutool Console Logging] Logger As Default.
2022-12-08 16:19:30 I/stdout: [2022-12-08 16:19:30] [DEBUG] cn.hutool.setting.SettingLoader: Load setting file [C:\Users\Administrator\Desktop\tata\data\love.huhu.bot\subscriptions.setting]
2022-12-08 16:19:30 I/stdout: [2022-12-08 16:19:30] [DEBUG] cn.hutool.setting.SettingLoader: Load setting file [C:\Users\Administrator\Desktop\tata\config\love.huhu.bot\config.setting]
2022-12-08 16:19:31 W/net.mamoe.mirai-api-http: Linked class net.mamoe.yamlkt.YamlElement in onebot-mirai-0.3.4-all.jar but plugin not depend on it.
2022-12-08 16:19:31 W/net.mamoe.mirai-api-http: Class loading logic may change in feature.
2022-12-08 16:19:31 E/net.mamoe.mirai-api-http: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'adapterSettings' in 'setting'
    host: localhost
                  ^ at line 30, column 20

net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'adapterSettings' in 'setting'
    host: localhost
                  ^ at line 30, column 20

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:181)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:537)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:85)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:47)
	at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:162)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:45)
	at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConfig(AbstractJvmPlugin.kt:59)
	at mirai-api-http-v2.6.2.mirai2.jar//net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:34)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:175)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:336)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:194)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:194)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for '1' in 'kotlin.collections.LinkedHashMap'
    host: localhost
        ^ at line 30, column 10

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:181)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:537)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.deserialize(serializerHelper.kt:170)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
	... 32 more
Caused by: java.lang.ClassCastException: class net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder cannot be cast to class net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder (net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder is in unnamed module of loader 'app'; net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder is in unnamed module of loader 'onebot-mirai-0.3.4-all.jar' @1b23822)
	at onebot-mirai-0.3.4-all.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:35)
	at onebot-mirai-0.3.4-all.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:30)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
	... 40 more
''

**Comment by rogue233** [comment]
配置文件：
[setting.txt](https://github.com/project-mirai/mirai-api-http/files/10183484/setting.txt)
运行日志：
[2022-12-08.log](https://github.com/project-mirai/mirai-api-http/files/10183485/2022-12-08.log)

**Comment by rogue233** [comment]
因为模本yml文件无法上传，我改了个后缀

**Comment by ryoii** [comment]
那你描述的修改是指修改了什么地方，而且我也没有看到配置文件中有出现报错中出现的 `127.0.0.1`

**Comment by rogue233** [comment]
原版就是如下：
    ## 配置文件中的值，全为默认值

    ## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
    adapters:
      - http
      - ws

    ## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
    ## 建议公网连接时开启
    enableVerify: true
    verifyKey: INITKEYopnF82al

    ## 开启一些调式信息
    debug: false

    ## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
    ## 开启后，接口中任何 sessionKey 不需要传递参数
    ## 若 console 中有多个 bot 登录，则行为未定义
    ## 确保 console 中只有一个 bot 登陆时启用
    singleMode: false

    ## 历史消息的缓存大小
    ## 同时，也是 http adapter 的消息队列容量
    cacheSize: 4096

    ## adapter 的单独配置，键名与 adapters 项配置相同
    adapterSettings:
      ## 详情看 http adapter 使用说明 配置
      http:
        host: localhost
        port: 8080
        cors: ["*"]
        unreadQueueMaxSize: 100
      
      ## 详情看 websocket adapter 使用说明 配置
      ws:
        host: localhost
        port: 8080
        reservedSyncId: -1

**Comment by rogue233** [comment]
> 那你描述的修改是指修改了什么地方，而且我也没有看到配置文件中有出现报错中出现的 `127.0.0.1`

我只是修改了verifyKey参数，其他的没有动。但是启动的时候会指出host: localhost这行命令有无，我将localhos改成127.0.0.1同样报错

**Comment by rogue233** [comment]
> 尝试移除 oneBot 插件

好吧，的确是这个原因_(:з」∠)_
多谢大佬！

**Comment by ryoii** [comment]
留意这个 issue #653

**Comment by 0f-0b** [comment]
更新到 2.7.0 之后出现了类似的报错，但 mirai-api-http 是唯一的插件。

<details>
<summary>日志</summary>

```log
2022-12-17 20:31:25 I/main: Starting mirai-console...
2022-12-17 20:31:25 I/main: 

==================================[ Mirai consosle 2.13.2 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2022-12-17 20:31:25 I/main: Backend: version 2.13.2, built on 2022-12-05 01:50:53.
2022-12-17 20:31:25 I/main: Frontend Terminal: version 2.13.2, provided by Mamoe Technologies
2022-12-17 20:31:25 I/main: Welcome to visit https://mirai.mamoe.net/
2022-12-17 20:31:25 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-12-17 20:31:25 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-12-17 20:31:25 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-12-17 20:32:27 I/plugin: Successfully loaded plugin mirai-api-http v2.7.0
2022-12-17 20:32:28 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-12-17 20:32:28 E/mirai-api-http: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'adapterSettings' in 'setting'
    host: localhost
                  ^ at line 9, column 20

net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'adapterSettings' in 'setting'
    host: localhost
                  ^ at line 9, column 20

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:181)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:537)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:85)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:47)
	at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:162)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:45)
	at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConfig(AbstractJvmPlugin.kt:59)
	at mirai-api-http-v2.7.0.mirai2.jar//net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:29)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:175)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:336)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for '1' in 'kotlin.collections.LinkedHashMap'
    host: localhost
        ^ at line 9, column 10

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:181)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:537)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.deserialize(serializerHelper.kt:170)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
	... 19 more
Caused by: java.lang.ClassCastException: class net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder cannot be cast to class net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder (net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder is in unnamed module of loader 'app'; net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder is in unnamed module of loader 'mirai-api-http-v2.7.0.mirai2.jar[private]' @29fe4840)
	at mirai-api-http-v2.7.0.mirai2.jar[private]//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:35)
	at mirai-api-http-v2.7.0.mirai2.jar[private]//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:30)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
	... 27 more

2022-12-17 20:32:28 I/main: 0 plugin(s) enabled.
```

</details>

<details>
<summary>setting.yml</summary>

```yml
adapters:
  - http
  - webhook
enableVerify: true
verifyKey: <verifyKey>
singleMode: true
adapterSettings:
  http:
    host: localhost
    port: 40031
    cors: []
    unreadQueueMaxSize: 0
  webhook:
    destinations:
      - "http://localhost:40032/"
```

</details>
