### ISSUE TITLE
/fetchMessage返回错误{"code":500,"msg":"Not a http session"}

### ISSUE THREAD

**Issue by H3AlO3** [project-mirai/mirai-api-http#658]
开启了singleMode，未开启verify，`/groupList`正常返回，`mcl`中消息正常被接收，`ws`同接口正常
`setting.yml`如下
```
adapters: 
  - http
debug: false
enableVerify: false
verifyKey: INITKEYpmdZ6CH3
singleMode: true
cacheSize: 4096
persistenceFactory: 'built-in'

adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8080
    cors: ["*"]
    unreadQueueMaxSize: 100
```
报错信息如下
```
2022-12-15 01:00:14 E/MAH Access: java.lang.RuntimeException: Not a http session
java.lang.RuntimeException: Not a http session
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.session.HttpAuthedSessionKt.unreadQueue(HttpAuthedSession.kt:45)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.dto.CountDTO.getUnreadQueue(parameters.kt:18)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$invoke$$inlined$httpAuthedGet$2$1.invokeSuspend(dsl.kt:201)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$invoke$$inlined$httpAuthedGet$2$1.invoke(dsl.kt)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$invoke$$inlined$httpAuthedGet$2$1.invoke(dsl.kt)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.routing.Routing.executeResult(Routing.kt:155)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.routing.Routing.interceptor(Routing.kt:39)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invokeSuspend(Authorization.kt:30)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invoke(Authorization.kt)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invoke(Authorization.kt)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.intercept(HttpRouterAccessHandler.kt:36)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.access$intercept(HttpRouterAccessHandler.kt:25)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invokeSuspend(HttpRouterAccessHandler.kt:91)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invoke(HttpRouterAccessHandler.kt)
	at mirai-api-http-2.6.2.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invoke(HttpRouterAccessHandler.kt)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:127)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
	at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.server.cio.CIOApplicationEngine$handleRequest$2.invokeSuspend(CIOApplicationEngine.kt:196)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```
访问的url是`http://localhost:8080/fetchMessage?sessionKey=&count=10`
麻烦帮忙看一下，谢谢！

**Comment by Simakeng** [comment]
明确了问题了，mcl -u 出来的版本仍然是2.6.7
手动更新到 2.7.0 无法读入adapter配置，整个mirai-http-api是一个不可用的状态,具体参看 #661
