### ISSUE TITLE
发送语音链接，导致mirai崩溃

### ISSUE THREAD

**Issue by CherryPeel** [project-mirai/mirai-api-http#690]
### 控制台崩溃页面
![image](https://user-images.githubusercontent.com/48341841/220122015-24884fe2-3c8a-405e-99e5-3b04c56e5b89.png)

已经装了https://github.com/project-mirai/mirai-silk-converter 这个插件，可将音频自动转换为QQ所支持的形式。

### 崩溃产生过程
发送百度tts的音频是可以正常发送的，百度的音频链接格式如下：[http://tsn.baidu.com/text2audio?tex=这是一个测试&tok=24.b1e2dd6d1caafc582528848bc54abc9b.2592000.1679484065.282335-30440650&cuid=a2fd6PYTHONdasjkhjgg245&ctp=1&lan=zh&spd=6&per=103](http://tsn.baidu.com/text2audio?tex=%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E6%B5%8B%E8%AF%95&tok=24.b1e2dd6d1caafc582528848bc54abc9b.2592000.1679484065.282335-30440650&cuid=a2fd6PYTHONdasjkhjgg245&ctp=1&lan=zh&spd=6&per=103)

![image](https://user-images.githubusercontent.com/48341841/220122742-a022095f-f4de-4e35-9e54-b9512fc86882.png)

报错的音频链接格式如下：[https://sayashi-vits-uma-genshin-honkai.hf.space/file=/tmp/tmpk13nrb_w/tmpujff2_ce.wav](https://sayashi-vits-uma-genshin-honkai.hf.space/file=/tmp/tmpk13nrb_w/tmpujff2_ce.wav)，音频是可以正常播放的，链接也是可访问的，但是发送mirai就崩溃。
![image](https://user-images.githubusercontent.com/48341841/220122627-375f562b-e103-4fc2-9804-8c1afc168a65.png)

## 详细信息
已安装插件：
![image](https://user-images.githubusercontent.com/48341841/220122457-15ecab35-0d1f-48f7-b645-62f57f6d69f1.png)

只使用了本项目的http接口。

报错日志：log链接：[https://pan.baidu.com/s/1OA1ZN5NiwEZ_5g3hEMghLg](https://pan.baidu.com/s/1OA1ZN5NiwEZ_5g3hEMghLg)
提取码：2a1v

此时mirai控制台日志并没有任何关于此错误的记录：
![image](https://user-images.githubusercontent.com/48341841/220124050-290a7b95-7ec9-4e3e-b950-22d4df4b4dfd.png)
![image](https://user-images.githubusercontent.com/48341841/220124081-43218b79-ed9d-4bc7-a95a-9e2c8fa3f89e.png)

[论坛中讨论的记录](https://mirai.mamoe.net/topic/2060/mp3%E5%92%8Cwav%E6%A0%BC%E5%BC%8F%E9%9F%B3%E9%A2%91%E4%BB%A5url%E6%A0%BC%E5%BC%8F%E5%8F%91%E9%80%81%E5%B0%B1%E6%8A%A5%E9%94%99-%E8%80%8C%E4%B8%94%E7%9B%B4%E6%8E%A5%E5%AF%BC%E8%87%B4mirai%E5%81%9C%E6%AD%A2%E5%B7%A5%E4%BD%9C/11?_=1676895554470)

**Comment by ryoii** [comment]
我感觉它比较像是 mirai-silk-converter 的问题

**Comment by ryoii** [comment]
测试了下，可以通过 mirai 下载，日志里最后崩溃的地方也在 mirai-silk-converter 的地址访问奔溃，排除没有数据的问题，大概是 native 哪里奔溃了，你本地正确安装 FFMPEG 了么

**Comment by cssxsh** [comment]
@Karlatemp 

我这边单元测试了一下，发现好像是 
没有正常 throw 异常, native 里 直接 printStackTrace 了
```
io.github.kasukusakura.silkcodec.CoderException: SKP_Silk_Encode returned -2
	at io.github.kasukusakura.silkcodec.SilkCoder.encode(Native Method)
	at io.github.kasukusakura.silkcodec.SilkCoder.encode(SilkCoder.java:46)
	at io.github.kasukusakura.silkcodec.SilkCoder.encode(SilkCoder.java:36)
	at io.github.kasukusakura.silkcodec.SilkCoder.encode(SilkCoder.java:63)
	at io.github.kasukusakura.silkcodec.AudioToSilkCoder.connect(AudioToSilkCoder.java:98)
	at io.github.kasukusakura.silkcodec.AudioToSilkCoder.connect(AudioToSilkCoder.java:25)
	at net.mamoe.mirai.silkconverter.Data.convert0(SilkConverter.kt:46)
	at net.mamoe.mirai.silkconverter.SilkConverterImpl$convert$2.invoke(SilkConverter.kt:62)
	at net.mamoe.mirai.silkconverter.SilkConverterImpl$convert$2.invoke(SilkConverter.kt:62)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```
