### ISSUE TITLE
mirai升级到v2.16.0-RC加载mirai api http v2.9.1异常

### ISSUE THREAD

**Issue by MDeath** [project-mirai/mirai-api-http#740]
mirai核心升级到`v2.16.0-RC`后初始化MiraiConsole失败，提示加载mirai api http v2.9.1时出现异常。
将`config.json`[^config.json]设置为稳定版，降级就没问题了。

```shell
  13:58:08 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  13:58:08 [INFO] Runtime: Java HotSpot(TM) 64-Bit Server VM 17.0.8 (arch: 64)
  13:58:08 [INFO] https://github.com/iTXTech/mirai-console-loader
  13:58:08 [INFO] This program is licensed under GNU AGPL v3
  13:58:08 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  13:58:08 [INFO] Verifying "net.mamoe:mirai-console" v2.16.0-RC
  13:58:09 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.16.0-RC
  13:58:09 [INFO] Verifying "net.mamoe:mirai-core-all" v2.16.0-RC
  13:58:09 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  13:58:09 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.65.01
2023-09-21 13:58:11 I/main: Starting mirai-console...
2023-09-21 13:58:11 I/main:

=================================[ Mirai console 2.16.0-RC ]==================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-09-21 13:58:11 I/main: Backend: version 2.16.0-RC, built on 2023-09-03 23:55:17.
2023-09-21 13:58:11 I/main: Frontend Terminal: version 2.16.0-RC, provided by Mamoe Technologies
2023-09-21 13:58:11 I/main: Welcome to visit https://mirai.mamoe.net/
2023-09-21 13:58:12 I/fix-protocol-version: 协议版本检查更新...
2023-09-21 13:58:12 I/fix-protocol-version: ANDROID_PAD load from
 file:///C:/Users/10643/Documents/Bot/Mirai/android_pad.json
2023-09-21 13:58:12 I/fix-protocol-version: 注册服务...
2023-09-21 13:58:12 I/fix-protocol-version: 服务配置文件:
 file:///C:/Users/10643/Documents/Bot/Mirai/KFCFactory.json
2023-09-21 13:58:12 I/plugin: Successfully loaded plugin fix-protocol-version v1.11.1
2023-09-21 13:58:12 I/plugin: Cannot load plugin mirai-api-http v2.9.1
2023-09-21 13:58:12 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading mirai-api-http v2.9.1
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:373)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:40)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:54)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:100)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:164)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:303)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.IllegalStateException: A JvmPlugin loaded by plugin.yml must has same description reference
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:362)
        ... 23 more
```

[^config.json]: 将mirai有关包的channel值从`maven`改为`maven-stable`即可。

**Comment by gebederry** [comment]
已于 https://github.com/mamoe/mirai/commit/323f6b363cdf5d6f69977d82ab0f2fb8ef4fe23a 修复。
